#
# Makefile for huawei misc driver.
#

obj-$(CONFIG_HW_INI) += hw-ini/
obj-$(CONFIG_HW_PM)  += hw-pm/
obj-$(CONFIG_HW_PS)  += hw-ps/
obj-$(CONFIG_HI1101_WIFI)   += oam-drv/
obj-$(CONFIG_HI1101_WIFI)   += hisiwifi/
obj-$(CONFIG_HW_CHR) += hw-chr/
