ccflags-y +=	-I$(srctree)/$(src)/../../config/nvim/include/gu/

obj-$(CONFIG_HISILICON_PLATFORM_NVIM)	+= hisilicon_platform_nvim.o
hisilicon_platform_nvim-y	:= balong_nvim.o nvim_appfunc.o nvim_fileoperateinterface.o nvim_commfunc.o
