EXTRA_CFLAGS   			+=-Idrivers/hisi/ipc_hi6xxx/
EXTRA_CFLAGS   			+= -Idrivers/hisi/mntn/
EXTRA_CFLAGS   			+= -Idrivers/hisi/modem_hi6xxx/drv/acore/timer

obj-y				:= drv_audio.o drv_usb.o drv_debug_led.o\
drv_mntn.o drv_hkadc.o drv_ipcm.o drv_version.o\
drv_dpm.o drv_nv.o drv_modem_bsp.o drv_sd.o\
drv_sec.o drv_pmu.o drv_sci.o drv_timer.o drv_wifi.o\
drv_socp.o drv_sysctrl.o drv_update.o\
drv_wdt.o drv_gpio.o drv_charge.o drv_mem_remap.o\
drv_oled.o drv_ifc.o drv_edma.o\
drv_misc_if.o drv_pwr_if.o drv_sd_if.o drv_bsp_if.o\
drv_bbp.o  drv_udi.o drv_ipf.o
