/*******************************************************************  
* (c) Copyright 2011-2012 Discretix Technologies Ltd.              *
* This software is protected by copyright, international           *
* treaties and patents.                                            *
* Use of this Software as part of or with the CryptoCell product   *
* is governed by the CryptoCell commercial end user license        *
* agreement ("CryptoCell EULA").                                   *
* It is possible that copies of this Software might be distributed *
* under some type of GNU General Public License ("GPL").           *
* Notwithstanding any such distribution under the terms of GPL,    *
* GPL does not govern the use of this Software as part of or with  *
* the CryptoCell product, for which a CryptoCell EULA is required. *
* If CryptoCell EULA allows any copy or reproduction of this       *
* Software, then such copy or reproduction must include this       *
* Copyright Notice as well as any other notices provided           *
* thereunder.                                                      *
********************************************************************/

#ifndef __DX_HOST_RGF_H__
#define __DX_HOST_RGF_H__

// --------------------------------------
// BLOCK: HOST_RGF
// --------------------------------------
#define DX_HOST_RGF_IRR_REG_OFFSET 	0xA00UL 
#define DX_HOST_RGF_IRR_DSCRPTR_COMPLETION_MASK_BIT_SHIFT  0x2UL
#define DX_HOST_RGF_IRR_DSCRPTR_COMPLETION_MASK_BIT_SIZE   0x1UL
#define DX_HOST_RGF_IRR_SRAM_TO_DIN_INT_BIT_SHIFT 	0x4UL
#define DX_HOST_RGF_IRR_SRAM_TO_DIN_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_DOUT_TO_SRAM_INT_BIT_SHIFT 	0x5UL
#define DX_HOST_RGF_IRR_DOUT_TO_SRAM_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_MEM_TO_DIN_INT_BIT_SHIFT 	0x6UL
#define DX_HOST_RGF_IRR_MEM_TO_DIN_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_DOUT_TO_MEM_INT_BIT_SHIFT 	0x7UL
#define DX_HOST_RGF_IRR_DOUT_TO_MEM_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_AXI_ERR_INT_BIT_SHIFT 	0x8UL
#define DX_HOST_RGF_IRR_AXI_ERR_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_PKA_EXP_INT_BIT_SHIFT 	0x9UL
#define DX_HOST_RGF_IRR_PKA_EXP_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_RNG_INT_BIT_SHIFT 	0xAUL
#define DX_HOST_RGF_IRR_RNG_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_DSCRPTR_WATERMARK_INT_BIT_SHIFT 	0x13UL
#define DX_HOST_RGF_IRR_DSCRPTR_WATERMARK_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_DSCRPTR_WATERMARK1_INT_BIT_SHIFT 	0x14UL
#define DX_HOST_RGF_IRR_DSCRPTR_WATERMARK1_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_CNTX_SWITCH_CNTR_EXPIRED_INT_BIT_SHIFT 	0x15UL
#define DX_HOST_RGF_IRR_CNTX_SWITCH_CNTR_EXPIRED_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IRR_HASH_CMP_ERROR_INT_BIT_SHIFT 	0x16UL
#define DX_HOST_RGF_IRR_HASH_CMP_ERROR_INT_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_REG_OFFSET 	0xA04UL 
#define DX_HOST_RGF_IMR_NOT_USED_MASK_BIT_SHIFT 	0x1UL
#define DX_HOST_RGF_IMR_NOT_USED_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_DSCRPTR_COMPLETION_MASK_BIT_SHIFT 	0x2UL
#define DX_HOST_RGF_IMR_DSCRPTR_COMPLETION_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_SRAM_TO_DIN_MASK_BIT_SHIFT 	0x4UL
#define DX_HOST_RGF_IMR_SRAM_TO_DIN_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_DOUT_TO_SRAM_MASK_BIT_SHIFT 	0x5UL
#define DX_HOST_RGF_IMR_DOUT_TO_SRAM_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_MEM_TO_DIN_MASK_BIT_SHIFT 	0x6UL
#define DX_HOST_RGF_IMR_MEM_TO_DIN_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_DOUT_TO_MEM_MASK_BIT_SHIFT 	0x7UL
#define DX_HOST_RGF_IMR_DOUT_TO_MEM_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_AXI_ERR_MASK_BIT_SHIFT 	0x8UL
#define DX_HOST_RGF_IMR_AXI_ERR_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_PKA_EXP_MASK_BIT_SHIFT 	0x9UL
#define DX_HOST_RGF_IMR_PKA_EXP_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_RNG_INT_MASK_BIT_SHIFT 	0xAUL
#define DX_HOST_RGF_IMR_RNG_INT_MASK_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_DSCRPTR_WATERMARK_MASK0_BIT_SHIFT 	0x13UL
#define DX_HOST_RGF_IMR_DSCRPTR_WATERMARK_MASK0_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_DSCRPTR_WATERMARK_MASK1_BIT_SHIFT 	0x14UL
#define DX_HOST_RGF_IMR_DSCRPTR_WATERMARK_MASK1_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_CNTX_SWITCH_CNTR_EXPIRED_BIT_SHIFT 	0x15UL
#define DX_HOST_RGF_IMR_CNTX_SWITCH_CNTR_EXPIRED_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_IMR_HASH_CMP_ERROR_BIT_SHIFT 	0x16UL
#define DX_HOST_RGF_IMR_HASH_CMP_ERROR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_REG_OFFSET 	0xA08UL 
#define DX_HOST_RGF_ICR_DSCRPTR_COMPLETION_BIT_SHIFT 	0x2UL
#define DX_HOST_RGF_ICR_DSCRPTR_COMPLETION_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_RESEREVED_BIT_SHIFT 	0x3UL
#define DX_HOST_RGF_ICR_RESEREVED_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_SRAM_TO_DIN_CLEAR_BIT_SHIFT 	0x4UL
#define DX_HOST_RGF_ICR_SRAM_TO_DIN_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_DOUT_TO_SRAM_CLEAR_BIT_SHIFT 	0x5UL
#define DX_HOST_RGF_ICR_DOUT_TO_SRAM_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_MEM_TO_DIN_CLEAR_BIT_SHIFT 	0x6UL
#define DX_HOST_RGF_ICR_MEM_TO_DIN_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_DOUT_TO_MEM_CLEAR_BIT_SHIFT 	0x7UL
#define DX_HOST_RGF_ICR_DOUT_TO_MEM_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_AXI_ERR_CLEAR_BIT_SHIFT 	0x8UL
#define DX_HOST_RGF_ICR_AXI_ERR_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_PKA_EXP_CLEAR_BIT_SHIFT 	0x9UL
#define DX_HOST_RGF_ICR_PKA_EXP_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_RNG_INT_CLEAR_BIT_SHIFT 	0xAUL
#define DX_HOST_RGF_ICR_RNG_INT_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_DSCRPTR_WATERMARK_QUEUE0_CLEAR_BIT_SHIFT 	0x13UL
#define DX_HOST_RGF_ICR_DSCRPTR_WATERMARK_QUEUE0_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_DSCRPTR_WATERMARK_QUEUE1_CLEAR_BIT_SHIFT 	0x14UL
#define DX_HOST_RGF_ICR_DSCRPTR_WATERMARK_QUEUE1_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_CNTX_SWITCH_CNTR_EXPIRED_CLEAR_BIT_SHIFT 	0x15UL
#define DX_HOST_RGF_ICR_CNTX_SWITCH_CNTR_EXPIRED_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ICR_HASH_CMP_ERROR_CLEAR_BIT_SHIFT 	0x16UL
#define DX_HOST_RGF_ICR_HASH_CMP_ERROR_CLEAR_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ENDIAN_REG_OFFSET 	0xA0CUL 
#define DX_HOST_RGF_ENDIAN_DOUT_WR_BG_BIT_SHIFT 	0x3UL
#define DX_HOST_RGF_ENDIAN_DOUT_WR_BG_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ENDIAN_DIN_RD_BG_BIT_SHIFT 	0x7UL
#define DX_HOST_RGF_ENDIAN_DIN_RD_BG_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ENDIAN_DOUT_WR_WBG_BIT_SHIFT 	0xBUL
#define DX_HOST_RGF_ENDIAN_DOUT_WR_WBG_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_ENDIAN_DIN_RD_WBG_BIT_SHIFT 	0xFUL
#define DX_HOST_RGF_ENDIAN_DIN_RD_WBG_BIT_SIZE 	0x1UL
#define DX_HOST_CC_SW_RESET_ALLOWED_REG_OFFSET 	0xA10UL 
#define DX_HOST_CC_SW_RESET_ALLOWED_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_CC_SW_RESET_ALLOWED_VALUE_BIT_SIZE 	0x1UL
#define DX_HOST_REGION_MASK_REG_OFFSET 	0xA18UL 
#define DX_HOST_REGION_MASK_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_REGION_MASK_VALUE_BIT_SIZE 	0x20UL
#define DX_HOST_RGF_CC_SW_RST_REG_OFFSET 	0xA20UL 
#define DX_HOST_RGF_CC_SW_RST_CC_SW_RST_REQ_BIT_SHIFT 	0x0UL
#define DX_HOST_RGF_CC_SW_RST_CC_SW_RST_REQ_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_CC_SW_RST_CC_SW_RST_FORCE_BIT_SHIFT 	0x1UL
#define DX_HOST_RGF_CC_SW_RST_CC_SW_RST_FORCE_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_CC_SW_RST_AXIS_SYSREQ_BIT_SHIFT 	0x2UL
#define DX_HOST_RGF_CC_SW_RST_AXIS_SYSREQ_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_CC_SW_RST_AXIM_SYSREQ_BIT_SHIFT 	0x3UL
#define DX_HOST_RGF_CC_SW_RST_AXIM_SYSREQ_BIT_SIZE 	0x1UL
#define DX_HOST_RGF_SIGNATURE_REG_OFFSET 	0xA24UL 
#define DX_HOST_RGF_SIGNATURE_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_RGF_SIGNATURE_VALUE_BIT_SIZE 	0x20UL
#define DX_HOST_BOOT_REG_OFFSET 	0xA28UL 
#define DX_HOST_BOOT_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_BOOT_VALUE_BIT_SIZE 	0x1FUL
#define DX_HOST_PROVISION_CONST_MASK_REG_OFFSET 	0xA30UL 
#define DX_HOST_PROVISION_CONST_MASK_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_PROVISION_CONST_MASK_VALUE_BIT_SIZE 	0x1UL
#define DX_HOST_ADDR_AXIM_CTRL_REG_OFFSET 	0xA34UL 
#define DX_HOST_ADDR_AXIM_CTRL_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_ADDR_AXIM_CTRL_VALUE_BIT_SIZE 	0x4UL
#define DX_HOST_CRYPTOKEY_SEL_REG_OFFSET 	0xA38UL 
#define DX_HOST_CRYPTOKEY_SEL_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_CRYPTOKEY_SEL_VALUE_BIT_SIZE 	0x2UL
#define DX_NVM_CC_BOOT_REG_OFFSET 	0xAA0UL 
#define DX_NVM_CC_BOOT_LARGE_RKEK_LOCAL_BIT_SHIFT 	0x1UL
#define DX_NVM_CC_BOOT_LARGE_RKEK_LOCAL_BIT_SIZE 	0x1UL
#define DX_NVM_CC_BOOT_HASH_IN_FUSES_LOCAL_BIT_SHIFT 	0x2UL
#define DX_NVM_CC_BOOT_HASH_IN_FUSES_LOCAL_BIT_SIZE 	0x1UL
#define DX_HOST_AIB_ADDR_REG_REG_OFFSET 	0xAA4UL 
#define DX_HOST_AIB_ADDR_REG_HOST_AIB_ADDR_REG_BIT_SHIFT 	0x0UL
#define DX_HOST_AIB_ADDR_REG_HOST_AIB_ADDR_REG_BIT_SIZE 	0xCUL
#define DX_HOST_AIB_ADDR_REG_READ_ACCESS_BIT_SHIFT 	0x10UL
#define DX_HOST_AIB_ADDR_REG_READ_ACCESS_BIT_SIZE 	0x1UL
#define DX_HOST_AIB_ADDR_REG_WRITE_ACCESS_BIT_SHIFT 	0x11UL
#define DX_HOST_AIB_ADDR_REG_WRITE_ACCESS_BIT_SIZE 	0x1UL
#define DX_HOST_AIB_WDATA_REG_REG_OFFSET 	0xAA8UL 
#define DX_HOST_AIB_WDATA_REG_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_AIB_WDATA_REG_VALUE_BIT_SIZE 	0x20UL
#define DX_HOST_AIB_RDATA_REG_REG_OFFSET 	0xAACUL 
#define DX_HOST_AIB_RDATA_REG_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_AIB_RDATA_REG_VALUE_BIT_SIZE 	0x20UL
#define DX_AIB_FUSE_PROG_COMPLETED_REG_OFFSET 	0xAB0UL 
#define DX_AIB_FUSE_PROG_COMPLETED_VALUE_BIT_SHIFT 	0x0UL
#define DX_AIB_FUSE_PROG_COMPLETED_VALUE_BIT_SIZE 	0x1UL
#define DX_AIB_FUSE_ACK_REG_OFFSET 	0xAB4UL 
#define DX_AIB_FUSE_ACK_VALUE_BIT_SHIFT 	0x0UL
#define DX_AIB_FUSE_ACK_VALUE_BIT_SIZE 	0x1UL
#define DX_AIB_DEBUG_STATUS_REG_OFFSET 	0xAB8UL 
#define DX_AIB_DEBUG_STATUS_FORBIDDEN_CPU_ACCESS_BIT_SHIFT 	0x0UL
#define DX_AIB_DEBUG_STATUS_FORBIDDEN_CPU_ACCESS_BIT_SIZE 	0x1UL
#define DX_AIB_DEBUG_STATUS_NVM_STATE_MACHINE_BIT_SHIFT 	0x1UL
#define DX_AIB_DEBUG_STATUS_NVM_STATE_MACHINE_BIT_SIZE 	0x4UL
#define DX_AIB_DEBUG_STATUS_RKEK_SM_BIT_SHIFT 	0x5UL
#define DX_AIB_DEBUG_STATUS_RKEK_SM_BIT_SIZE 	0x4UL
#define DX_LCS_IS_VALID_REG_OFFSET 	0xABCUL 
#define DX_LCS_IS_VALID_VALUE_BIT_SHIFT 	0x0UL
#define DX_LCS_IS_VALID_VALUE_BIT_SIZE 	0x1UL
#define DX_HOST_SESSION_KEY0_REG_OFFSET 	0xAC0UL 
#define DX_HOST_SESSION_KEY0_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_SESSION_KEY0_VALUE_BIT_SIZE 	0x20UL
#define DX_HOST_SESSION_KEY1_REG_OFFSET 	0xAC4UL 
#define DX_HOST_SESSION_KEY1_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_SESSION_KEY1_VALUE_BIT_SIZE 	0x20UL
#define DX_HOST_SESSION_KEY2_REG_OFFSET 	0xAC8UL 
#define DX_HOST_SESSION_KEY2_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_SESSION_KEY2_VALUE_BIT_SIZE 	0x20UL
#define DX_HOST_SESSION_KEY3_REG_OFFSET 	0xACCUL 
#define DX_HOST_SESSION_KEY3_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_SESSION_KEY3_VALUE_BIT_SIZE 	0x20UL
#define DX_HOST_SEESION_KEY_IS_VALID_REG_OFFSET 	0xAD0UL 
#define DX_HOST_SEESION_KEY_IS_VALID_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_SEESION_KEY_IS_VALID_VALUE_BIT_SIZE 	0x1UL
#define DX_LCS_REG_REG_OFFSET 	0xAD4UL 
#define DX_LCS_REG_LCS_REG_BIT_SHIFT 	0x0UL
#define DX_LCS_REG_LCS_REG_BIT_SIZE 	0x8UL
#define DX_LCS_REG_ERROR_KDR_ZERO_CNT_BIT_SHIFT 	0x8UL
#define DX_LCS_REG_ERROR_KDR_ZERO_CNT_BIT_SIZE 	0x1UL
#define DX_LCS_REG_ERROR_PROV_ZERO_CNT_BIT_SHIFT 	0x9UL
#define DX_LCS_REG_ERROR_PROV_ZERO_CNT_BIT_SIZE 	0x1UL
#define DX_LCS_REG_RESREVED_BIT_SHIFT 	0xAUL
#define DX_LCS_REG_RESREVED_BIT_SIZE 	0x16UL
#define DX_HOST_CPC_SECURITY_DISABLE_REG_OFFSET 	0xAD8UL 
#define DX_HOST_CPC_SECURITY_DISABLE_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_CPC_SECURITY_DISABLE_VALUE_BIT_SIZE 	0x1UL
#define DX_HOST_AO_CC_STATE_COUNTER_REG_OFFSET 	0xADCUL 
#define DX_HOST_AO_CC_STATE_COUNTER_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_AO_CC_STATE_COUNTER_VALUE_BIT_SIZE 	0x20UL
#define DX_HOST_CC_AO_STATE_COUNTER_INC_REG_OFFSET 	0xAE0UL 
#define DX_HOST_CC_AO_STATE_COUNTER_INC_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_CC_AO_STATE_COUNTER_INC_VALUE_BIT_SIZE 	0x1UL
#define DX_HOST_AO_CC_IS_SD_REG_OFFSET 	0xAE4UL 
#define DX_HOST_AO_CC_IS_SD_VALUE_BIT_SHIFT 	0x0UL
#define DX_HOST_AO_CC_IS_SD_VALUE_BIT_SIZE 	0x1UL
#define DX_SRAM_DATA_REG_OFFSET 	0xF00UL 
#define DX_SRAM_DATA_VALUE_BIT_SHIFT 	0x0UL
#define DX_SRAM_DATA_VALUE_BIT_SIZE 	0x20UL
#define DX_SRAM_ADDR_REG_OFFSET 	0xF04UL 
#define DX_SRAM_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_SRAM_ADDR_VALUE_BIT_SIZE 	0xFUL
#define DX_SRAM_DATA_READY_REG_OFFSET 	0xF08UL 
#define DX_SRAM_DATA_READY_VALUE_BIT_SHIFT 	0x0UL
#define DX_SRAM_DATA_READY_VALUE_BIT_SIZE 	0x1UL

#endif //__DX_HOST_RGF_H__


