EXTRA_CFLAGS   			+=-Idrivers/hisi/ipc_hi6xxx/
EXTRA_CFLAGS   			+=-Idrivers/hisi/modem_hi6xxx/drv/acore/common/
EXTRA_CFLAGS   			+= -Idrivers/hisi/mntn

obj-y		+= bsp_icc.o
obj-y		+= icc_test.o
