EXTRA_CFLAGS                    += -Idrivers/usb/gadget/
EXTRA_CFLAGS                    += -Idrivers/usb/susb/
EXTRA_CFLAGS                    += -Idrivers/hisi/modem_hi6xxx/drv/acore/udi/

obj-$(CONFIG_HISILICON_PLATFORM_USB)	+= usb_shell.o acm_ldisc.o acm_ncopy_io.o

