obj-$(CONFIG_PM_DEVFREQ)	+= devfreq.o
obj-$(CONFIG_DEVFREQ_GOV_SIMPLE_ONDEMAND)	+= governor_simpleondemand.o
obj-$(CONFIG_DEVFREQ_GOV_MALI_ONDEMAND)	+= governor_maliondemand.o
obj-$(CONFIG_DEVFREQ_GOV_PERFORMANCE)	+= governor_performance.o
obj-$(CONFIG_DEVFREQ_GOV_POWERSAVE)	+= governor_powersave.o
obj-$(CONFIG_DEVFREQ_GOV_USERSPACE)	+= governor_userspace.o
obj-$(CONFIG_DEVFREQ_GOV_PM_QOS)	+= governor_pm_qos.o

# DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS4_BUS_DEVFREQ)	+= exynos4_bus.o
obj-$(CONFIG_HI6XXX_DDR_DEVFREQ)		+= hi6xxx_ddr_devfreq.o
obj-$(CONFIG_HI6XXX_DDR_DEVFREQ_DEBUGFS)	+= hi6xxx_ddr_devfreq_debugfs.o
obj-$(CONFIG_HI3XXX_DDR_DEVFREQ)		+= hi3xxx_ddr_devfreq.o
obj-$(CONFIG_HI3XXX_DDR_DEVFREQ_DEBUGFS)	+= hi3xxx_ddr_devfreq_debugfs.o
