PSDIR = ..

MODEM_DIR := $(srctree)/$(src)/../..

ifeq ($(KERNEL_ARM_TYPE), arm64)
EXTRA_CFLAGS += -Iarch/arm64/include/asm
else
EXTRA_CFLAGS += -Iarch/arm/include/asm
endif
EXTRA_CFLAGS += -Iinclude/linux
EXTRA_CFLAGS += -Iinclude/generated
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/med
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/codec
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/osa
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/om
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/nvim
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/log
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/om
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/si
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/usimm
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/errno
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/socp
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/nvim
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/lt/acore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/lt/common/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/taf
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/tlps
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/gups
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/ttf
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/oam
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/nas
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/was
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/nas
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/osa
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/nvim/include/gu
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/inc/gu
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/as/gu/ttf/TTFComm/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/LINK/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/DICC/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/DIPC/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/FLOWCTRL/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/IMM/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/MEMCTRL/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/MUX/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/NFEXT/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/NDIS/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/ND/IPCOMM/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/ND/NDSERVER/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/PPP/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/ps/comm/comm/STL/Inc
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/om
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/comm/om

EXTRA_CFLAGS +=  -DVOS_LINUX=4 -DOSA_CPU_ACPU=1 -DVOS_OS_VER=VOS_LINUX -DVOS_OSA_CPU=OSA_CPU_ACPU -D__LOG_RELEASE__ -DBSP_CORE_APP -DGU_MODE -DMSP_SUPPORT_USB_VCOM1 -DMSP_SUPPORT_USB_VCOM2 -DVOS_DOPRA_VER=2 -DNDIS_RELEASE -DBALONG_PHY_V200=2 -DBALONG_PHY_V300=3 -DBALONG_PHY_VER=BALONG_PHY_V300 -DBALONG_CHIP_V200=2 -DBALONG_CHIP_V300=3 -DBALONG_CHIP_V500=4 -DBALONG_CHIP_VER=BALONG_CHIP_V500 -DMSP_GUNAS_AT_UNITE
ifneq ($(KERNEL_ARM_TYPE), arm64)
EXTRA_CFLAGS += -D__LINUX_ARM_ARCH__=7 -march=armv7-a -Uarm
endif

ifeq ($(strip $(OBB_UE_MODE_CDMA)),true)
EXTRA_CFLAGS += -DFEATURE_UE_MODE_CDMA=FEATURE_ON
else
EXTRA_CFLAGS += -DFEATURE_UE_MODE_CDMA=FEATURE_OFF
endif

EXTRA_CFLAGS += -fsigned-char 

gups-objs := $(PSDIR)/comm/comm/DICC/Src/Dicc.o
gups-objs += $(PSDIR)/comm/comm/DIPC/Src/PsDipc.o
gups-objs += $(PSDIR)/comm/comm/MUX/Src/PsMux.o
gups-objs += $(PSDIR)/comm/comm/FLOWCTRL/Src/ACpuLoad.o
gups-objs += $(PSDIR)/comm/comm/FLOWCTRL/Src/Fc.o
gups-objs += $(PSDIR)/comm/comm/FLOWCTRL/Src/FcACore.o
gups-objs += $(PSDIR)/comm/comm/FLOWCTRL/Src/FcACoreCReset.o
gups-objs += $(PSDIR)/comm/comm/IMM/Src/IMMmemMntn.o
gups-objs += $(PSDIR)/comm/comm/IMM/Src/IMMmemRB.o
gups-objs += $(PSDIR)/comm/comm/IMM/Src/IMMmemZC.o
gups-objs += $(PSDIR)/comm/comm/LINK/Src/TTFLink.o
gups-objs += $(PSDIR)/comm/comm/LINK/Src/TTFUtil.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/acf.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/async.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/auth.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/chap.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/hdlc.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ipcp.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/lcp.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/link.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/pap.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_fsm.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_mbuf.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_public.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/pppid.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/proto.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/throughput.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/hdlc_hardware.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/hdlc_software.o

# MemCtrl is only used by ppp on Acpu(32bit)
gups-objs += $(PSDIR)/comm/comm/MEMCTRL/Src/TTFMemCtrl.o


# Stub For Taf And Ndis
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_atcmd.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_init.o
gups-objs += $(PSDIR)/comm/comm/PPP/Src/ppp_input.o

gups-objs += $(PSDIR)/comm/comm/NFEXT/IpsMntn.o
gups-objs += $(PSDIR)/comm/comm/NFEXT/NetfilterEx.o
gups-objs += $(PSDIR)/comm/comm/NFEXT/NetfilterExCtrl.o
gups-objs += $(PSDIR)/comm/comm/HISOCKET/Src/hisocket.o


ifeq ($(CFG_TTF_SKB_EXP),NO)
gups-objs += $(PSDIR)/comm/comm/IMM/Src/IMMmem_PS.o    
endif

obj-y  := gups.o



