/*******************************************************************  
* (c) Copyright 2011-2012 Discretix Technologies Ltd.              *
* This software is protected by copyright, international           *
* treaties and patents.                                            *
* Use of this Software as part of or with the CryptoCell product   *
* is governed by the CryptoCell commercial end user license        *
* agreement ("CryptoCell EULA").                                   *
* It is possible that copies of this Software might be distributed *
* under some type of GNU General Public License ("GPL").           *
* Notwithstanding any such distribution under the terms of GPL,    *
* GPL does not govern the use of this Software as part of or with  *
* the CryptoCell product, for which a CryptoCell EULA is required. *
* If CryptoCell EULA allows any copy or reproduction of this       *
* Software, then such copy or reproduction must include this       *
* Copyright Notice as well as any other notices provided           *
* thereunder.                                                      *
********************************************************************/

#ifndef __DX_ENV_H__
#define __DX_ENV_H__

// --------------------------------------
// BLOCK: ENV_REGS
// --------------------------------------
#define DX_ENV_CC_GPI_REG_OFFSET 	0x018UL 
#define DX_ENV_CC_GPI_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_GPI_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CC_GPO_REG_OFFSET 	0x01CUL 
#define DX_ENV_CC_GPO_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_GPO_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_PKA_DEBUG_MODE_REG_OFFSET 	0x024UL 
#define DX_ENV_PKA_DEBUG_MODE_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_PKA_DEBUG_MODE_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_SCAN_MODE_REG_OFFSET 	0x030UL 
#define DX_ENV_SCAN_MODE_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_SCAN_MODE_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_ALLOW_SCAN_REG_OFFSET 	0x034UL 
#define DX_ENV_CC_ALLOW_SCAN_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_ALLOW_SCAN_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_HOST_CC_EXT_INT_REG_OFFSET 	0x038UL 
#define DX_ENV_HOST_CC_EXT_INT_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_HOST_CC_EXT_INT_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_HOST_INT_REG_OFFSET 	0x0A0UL 
#define DX_ENV_CC_HOST_INT_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_HOST_INT_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_RST_N_REG_OFFSET 	0x0A8UL 
#define DX_ENV_CC_RST_N_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_RST_N_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_RST_OVERRIDE_REG_OFFSET 	0x0ACUL 
#define DX_ENV_RST_OVERRIDE_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_RST_OVERRIDE_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_HOST_EXT_ACK_REG_OFFSET 	0x0B0UL 
#define DX_ENV_CC_HOST_EXT_ACK_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_HOST_EXT_ACK_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_POR_N_ADDR_REG_OFFSET 	0x0E0UL 
#define DX_ENV_CC_POR_N_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_POR_N_ADDR_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_WARM_BOOT_REG_OFFSET 	0x0E4UL 
#define DX_ENV_CC_WARM_BOOT_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_WARM_BOOT_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_COLD_BOOT_REG_OFFSET 	0x0E8UL 
#define DX_ENV_CC_COLD_BOOT_CC_COLD_BOOT_FULL_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_COLD_BOOT_CC_COLD_BOOT_FULL_BIT_SIZE 	0x1UL
#define DX_ENV_CC_COLD_BOOT_CC_COLD_BOOT_SEMI_BIT_SHIFT 	0x1UL
#define DX_ENV_CC_COLD_BOOT_CC_COLD_BOOT_SEMI_BIT_SIZE 	0x1UL
#define DX_ENV_CC_AO_MODEL_RST_REG_OFFSET 	0x0ECUL 
#define DX_ENV_CC_AO_MODEL_RST_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_AO_MODEL_RST_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_BM_LOWER_BOUND_ADDR_REG_OFFSET 	0x0F0UL 
#define DX_ENV_CC_BM_LOWER_BOUND_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_BM_LOWER_BOUND_ADDR_VALUE_BIT_SIZE 	0x14UL
#define DX_ENV_CC_BM_UPPER_BOUND_ADDR_REG_OFFSET 	0x0F4UL 
#define DX_ENV_CC_BM_UPPER_BOUND_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_BM_UPPER_BOUND_ADDR_VALUE_BIT_SIZE 	0x14UL
#define DX_ENV_CC_BM_ENB_ADDR_REG_OFFSET 	0x0F8UL 
#define DX_ENV_CC_BM_ENB_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_BM_ENB_ADDR_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_COLD_RST_REG_OFFSET 	0x0FCUL 
#define DX_ENV_CC_COLD_RST_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_COLD_RST_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_BM_ERR_ACK_ADDR_REG_OFFSET 	0x100UL 
#define DX_ENV_CC_BM_ERR_ACK_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_BM_ERR_ACK_ADDR_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_BM_CC_ERR_ADDR_REG_OFFSET 	0x104UL 
#define DX_ENV_BM_CC_ERR_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_BM_CC_ERR_ADDR_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_DUMMY_ADDR_REG_OFFSET 	0x108UL 
#define DX_ENV_DUMMY_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_DUMMY_ADDR_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_COUNTER_CLR_REG_OFFSET 	0x118UL 
#define DX_ENV_COUNTER_CLR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_COUNTER_CLR_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_COUNTER_RD_REG_OFFSET 	0x11CUL 
#define DX_ENV_COUNTER_RD_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_COUNTER_RD_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CC_SECOND_BM_LOWER_BOUND_ADDR_REG_OFFSET 	0x120UL 
#define DX_ENV_CC_SECOND_BM_LOWER_BOUND_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_SECOND_BM_LOWER_BOUND_ADDR_VALUE_BIT_SIZE 	0x14UL
#define DX_ENV_CC_SECOND_BM_UPPER_BOUND_ADDR_REG_OFFSET 	0x124UL 
#define DX_ENV_CC_SECOND_BM_UPPER_BOUND_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_SECOND_BM_UPPER_BOUND_ADDR_VALUE_BIT_SIZE 	0x14UL
#define DX_ENV_CC_SECOND_BM_ENB_ADDR_REG_OFFSET 	0x128UL 
#define DX_ENV_CC_SECOND_BM_ENB_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_SECOND_BM_ENB_ADDR_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_SECOND_BM_ERR_ACK_ADDR_REG_OFFSET 	0x12CUL 
#define DX_ENV_CC_SECOND_BM_ERR_ACK_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_SECOND_BM_ERR_ACK_ADDR_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_SECOND_BM_CC_ERR_ADDR_REG_OFFSET 	0x130UL 
#define DX_ENV_SECOND_BM_CC_ERR_ADDR_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_SECOND_BM_CC_ERR_ADDR_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_RNG_DEBUG_ENABLE_REG_OFFSET 	0x430UL 
#define DX_ENV_RNG_DEBUG_ENABLE_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_RNG_DEBUG_ENABLE_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_LCS_REG_OFFSET 	0x43CUL 
#define DX_ENV_CC_LCS_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_LCS_VALUE_BIT_SIZE 	0x8UL
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_REG_OFFSET 	0x440UL 
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_IS_CM_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_IS_CM_BIT_SIZE 	0x1UL
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_IS_DM_BIT_SHIFT 	0x1UL
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_IS_DM_BIT_SIZE 	0x1UL
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_IS_SECURE_BIT_SHIFT 	0x2UL
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_IS_SECURE_BIT_SIZE 	0x1UL
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_IS_RMA_BIT_SHIFT 	0x3UL
#define DX_ENV_CC_IS_CM_DM_SECURE_RMA_IS_RMA_BIT_SIZE 	0x1UL
#define DX_ENV_DCU_EN_REG_OFFSET 	0x444UL 
#define DX_ENV_DCU_EN_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_DCU_EN_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CC_LCS_IS_VALID_REG_OFFSET 	0x448UL 
#define DX_ENV_CC_LCS_IS_VALID_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_LCS_IS_VALID_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_CRYPTOKEY_0_REG_OFFSET 	0x450UL 
#define DX_ENV_CRYPTOKEY_0_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CRYPTOKEY_0_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CRYPTOKEY_1_REG_OFFSET 	0x454UL 
#define DX_ENV_CRYPTOKEY_1_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CRYPTOKEY_1_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CRYPTOKEY_2_REG_OFFSET 	0x458UL 
#define DX_ENV_CRYPTOKEY_2_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CRYPTOKEY_2_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CRYPTOKEY_3_REG_OFFSET 	0x45CUL 
#define DX_ENV_CRYPTOKEY_3_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CRYPTOKEY_3_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CRYPTOKEY_4_REG_OFFSET 	0x460UL 
#define DX_ENV_CRYPTOKEY_4_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CRYPTOKEY_4_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CRYPTOKEY_5_REG_OFFSET 	0x464UL 
#define DX_ENV_CRYPTOKEY_5_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CRYPTOKEY_5_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CRYPTOKEY_6_REG_OFFSET 	0x468UL 
#define DX_ENV_CRYPTOKEY_6_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CRYPTOKEY_6_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_CRYPTOKEY_7_REG_OFFSET 	0x46CUL 
#define DX_ENV_CRYPTOKEY_7_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CRYPTOKEY_7_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_POWER_DOWN_REG_OFFSET 	0x478UL 
#define DX_ENV_POWER_DOWN_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_POWER_DOWN_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_POWER_DOWN_EN_REG_OFFSET 	0x47CUL 
#define DX_ENV_POWER_DOWN_EN_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_POWER_DOWN_EN_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_DCU_H_EN_REG_OFFSET 	0x484UL 
#define DX_ENV_DCU_H_EN_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_DCU_H_EN_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_VERSION_REG_OFFSET 	0x488UL 
#define DX_ENV_VERSION_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_VERSION_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_FUSE_AIB_1K_OFFSET_REG_OFFSET 	0x48CUL 
#define DX_ENV_FUSE_AIB_1K_OFFSET_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_FUSE_AIB_1K_OFFSET_VALUE_BIT_SIZE 	0x2UL
#define DX_ENV_RESET_AO_MODEL_REG_OFFSET 	0x494UL 
#define DX_ENV_RESET_AO_MODEL_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_RESET_AO_MODEL_VALUE_BIT_SIZE 	0x2UL
#define DX_ENV_CC_SEP_DEBUG_EN_REG_OFFSET 	0x4A0UL 
#define DX_ENV_CC_SEP_DEBUG_EN_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_CC_SEP_DEBUG_EN_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_AO_OUT_SESSION_KEY_0_REG_OFFSET 	0x4B0UL 
#define DX_ENV_AO_OUT_SESSION_KEY_0_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_AO_OUT_SESSION_KEY_0_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_AO_OUT_SESSION_KEY_1_REG_OFFSET 	0x4B4UL 
#define DX_ENV_AO_OUT_SESSION_KEY_1_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_AO_OUT_SESSION_KEY_1_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_AO_OUT_SESSION_KEY_2_REG_OFFSET 	0x4B8UL 
#define DX_ENV_AO_OUT_SESSION_KEY_2_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_AO_OUT_SESSION_KEY_2_VALUE_BIT_SIZE 	0x20UL
#define DX_ENV_AO_OUT_SESSION_KEY_3_REG_OFFSET 	0x4BCUL 
#define DX_ENV_AO_OUT_SESSION_KEY_3_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_AO_OUT_SESSION_KEY_3_VALUE_BIT_SIZE 	0x20UL
// --------------------------------------
// BLOCK: ENV_CC_MEMORIES
// --------------------------------------
#define DX_ENV_FUSE_READY_REG_OFFSET 	0x414UL 
#define DX_ENV_FUSE_READY_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_FUSE_READY_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_PERF_RAM_MASTER_REG_OFFSET 	0x500UL 
#define DX_ENV_PERF_RAM_MASTER_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_PERF_RAM_MASTER_VALUE_BIT_SIZE 	0x1UL
#define DX_ENV_PERF_RAM_ADDR_HIGH4_REG_OFFSET 	0x504UL 
#define DX_ENV_PERF_RAM_ADDR_HIGH4_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_PERF_RAM_ADDR_HIGH4_VALUE_BIT_SIZE 	0x2UL
#define DX_ENV_FUSES_RAM_REG_OFFSET 	0x800UL 
#define DX_ENV_FUSES_RAM_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_FUSES_RAM_VALUE_BIT_SIZE 	0x20UL
// --------------------------------------
// BLOCK: ENV_PERF_RAM_BASE
// --------------------------------------
#define DX_ENV_PERF_RAM_BASE_REG_OFFSET 	0x000UL 
#define DX_ENV_PERF_RAM_BASE_VALUE_BIT_SHIFT 	0x0UL
#define DX_ENV_PERF_RAM_BASE_VALUE_BIT_SIZE 	0x20UL

#endif /*__DX_ENV_H__*/


