ccflags-y +=    -I$(srctree)/drivers/mmc/host
ccflags-y +=    -I$(srctree)/drivers/hisi/mntn
ccflags-y +=    -I$(srctree)/drivers/tzdriver

obj-y                   	+= hi6xxx-modem.o
obj-y						+= hi6xxx_loadmodem.o
obj-y	                    += hi6xxx-power.o

