obj-y +=hisi_mailbox.o
obj-$(CONFIG_HISI_MAILBOX_DEBUGFS) +=hisi_mailbox_debugfs.o
obj-y +=hisi_rproc.o
obj-y +=hisi_rproc_test.o
obj-$(CONFIG_HISI_RPROC_DEBUGFS) +=hisi_rproc_debugfs.o
obj-$(CONFIG_HI3XXX_MAILBOX) +=hi3xxx_mailbox_dev.o
obj-$(CONFIG_HI6XXX_MAILBOX) +=hi6xxx_mailbox_dev.o
obj-$(CONFIG_HI6XXX_MAILBOX) +=ipc_msg.o

