#
# Generic Hardware Spinlock framework
#

obj-$(CONFIG_HWSPINLOCK)		+= hwspinlock_core.o
obj-$(CONFIG_HWSPINLOCK_OMAP)		+= omap_hwspinlock.o
obj-$(CONFIG_HSEM_U8500)		+= u8500_hsem.o
obj-$(CONFIG_HWSPINLOCK_HI3XXX)		+= hi3xxx_hwspinlock.o
