subdir-ccflags-y   			+= -I$(srctree)/drivers/hisi/modem_hi6xxx/include/drv/acore/
subdir-ccflags-y   			+= -I$(srctree)/drivers/hisi/modem_hi6xxx/include/drv/common/
subdir-ccflags-y   			+= -I$(srctree)/drivers/hisi/modem_hi6xxx/drv/comm/inc/
subdir-ccflags-y   			+= -I$(srctree)/drivers/hisi/modem_hi6xxx/config/product/$(OBB_PRODUCT_NAME)/config
subdir-ccflags-y   			+= -I$(srctree)/drivers/hisi/modem_hi6xxx/include/nv/tl/drv/
subdir-ccflags-y   			+= -I$(srctree)/drivers/hisi/modem_hi6xxx/include/nv/tl/oam/
subdir-ccflags-y   			+= -I$(srctree)/drivers/hisi/modem_hi6xxx/include/nv/tl/lps/
subdir-ccflags-y   			+= -I$(srctree)/drivers/hisi/modem_hi6xxx/config/nvim/include/gu/

obj-$(CONFIG_HISI_BALONG_MODEM_HI6XXX)  += drv/
obj-$(CONFIG_HISI_BALONG_MODEM_HI6XXX)  += oam/ ps/ taf/
