ccflags-y += -Idrivers/media/huawei/camera/isp
ccflags-y += -Idrivers/media/huawei/camera/io
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/platform
ccflags-y += -Idrivers/media/huawei/camera/platform/k3v3plus
ccflags-y += -Idrivers/media/huawei/camera/csi

obj-y += ovisp2.3.o
obj-y += isp_ops.o

