/*!
 *****************************************************************************
 *
 * @File       msvdx_pin_test_regs.h
 * @Description    This file contains the MSVDX_PIN_TEST_REGS_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__MSVDX_PIN_TEST_REGS_H__)
#define __MSVDX_PIN_TEST_REGS_H__

#ifdef __cplusplus
extern "C" {
#endif


#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_OFFSET		(0x0000)

/* MSVDX_PIN_TEST, MSVDX_IDLE_STATUS, CLK_ENABLE_IDLE_ERROR
*/
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_CLK_ENABLE_IDLE_ERROR_MASK		(0x00000004)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_CLK_ENABLE_IDLE_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_CLK_ENABLE_IDLE_ERROR_SHIFT		(2)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_CLK_ENABLE_IDLE_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_CLK_ENABLE_IDLE_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_CLK_ENABLE_IDLE_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MSVDX_IDLE_STATUS, MSVDX_IDLE_VALUE
*/
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_VALUE_MASK		(0x00000002)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_VALUE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_VALUE_SHIFT		(1)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_VALUE_LENGTH		(1)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_VALUE_DEFAULT		(0)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_VALUE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MSVDX_IDLE_STATUS, MSVDX_IDLE_EDGE
*/
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_EDGE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_EDGE_SHIFT		(0)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_MSVDX_IDLE_STATUS_MSVDX_IDLE_EDGE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_OFFSET		(0x0004)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VDEB_SCALE_BE_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_BE_CLK_STATUS_MASK		(0x00080000)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_BE_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_BE_CLK_STATUS_SHIFT		(19)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_BE_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_BE_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_BE_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VDEB_SCALE_FE_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_FE_CLK_STATUS_MASK		(0x00040000)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_FE_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_FE_CLK_STATUS_SHIFT		(18)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_FE_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_FE_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_SCALE_FE_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VDEB_PROCESS2_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS2_CLK_STATUS_MASK		(0x00020000)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS2_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS2_CLK_STATUS_SHIFT		(17)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS2_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS2_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS2_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VDEB_PROCESS1_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS1_CLK_STATUS_MASK		(0x00010000)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS1_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS1_CLK_STATUS_SHIFT		(16)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS1_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS1_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_PROCESS1_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VDEB_ACCESS2_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS2_CLK_STATUS_MASK		(0x00008000)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS2_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS2_CLK_STATUS_SHIFT		(15)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS2_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS2_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS2_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VDEB_ACCESS1_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS1_CLK_STATUS_MASK		(0x00004000)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS1_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS1_CLK_STATUS_SHIFT		(14)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS1_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS1_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDEB_ACCESS1_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VDMC2_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC2_CLK_STATUS_MASK		(0x00002000)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC2_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC2_CLK_STATUS_SHIFT		(13)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC2_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC2_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC2_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VDMC1_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC1_CLK_STATUS_MASK		(0x00001000)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC1_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC1_CLK_STATUS_SHIFT		(12)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC1_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC1_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VDMC1_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VEC_ITRANS_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_ITRANS_CLK_STATUS_MASK		(0x00000800)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_ITRANS_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_ITRANS_CLK_STATUS_SHIFT		(11)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_ITRANS_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_ITRANS_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_ITRANS_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VEC_DEC_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_DEC_CLK_STATUS_MASK		(0x00000400)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_DEC_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_DEC_CLK_STATUS_SHIFT		(10)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_DEC_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_DEC_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_DEC_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VEC_BE_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_BE_CLK_STATUS_MASK		(0x00000200)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_BE_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_BE_CLK_STATUS_SHIFT		(9)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_BE_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_BE_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_BE_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VEC_REG_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_REG_CLK_STATUS_MASK		(0x00000100)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_REG_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_REG_CLK_STATUS_SHIFT		(8)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_REG_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_REG_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_REG_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VEC_FE_GRP2_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP2_CLK_STATUS_MASK		(0x00000080)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP2_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP2_CLK_STATUS_SHIFT		(7)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP2_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP2_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP2_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VEC_FE_GRP1_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP1_CLK_STATUS_MASK		(0x00000040)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP1_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP1_CLK_STATUS_SHIFT		(6)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP1_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP1_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_GRP1_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, VEC_FE_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_CLK_STATUS_MASK		(0x00000020)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_CLK_STATUS_SHIFT		(5)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_VEC_FE_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, MTX_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MTX_CLK_STATUS_MASK		(0x00000010)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MTX_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MTX_CLK_STATUS_SHIFT		(4)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MTX_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MTX_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MTX_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, REG_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_REG_CLK_STATUS_MASK		(0x00000008)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_REG_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_REG_CLK_STATUS_SHIFT		(3)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_REG_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_REG_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_REG_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, DMAC_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_DMAC_CLK_STATUS_MASK		(0x00000004)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_DMAC_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_DMAC_CLK_STATUS_SHIFT		(2)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_DMAC_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_DMAC_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_DMAC_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, MEM_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MEM_CLK_STATUS_MASK		(0x00000002)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MEM_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MEM_CLK_STATUS_SHIFT		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MEM_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MEM_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_MEM_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_STATUS, CORE1_CLK_STATUS
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_CORE1_CLK_STATUS_MASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_CORE1_CLK_STATUS_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_CORE1_CLK_STATUS_SHIFT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_CORE1_CLK_STATUS_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_CORE1_CLK_STATUS_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_STATUS_CORE1_CLK_STATUS_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_OFFSET		(0x0008)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VDEB_SCALE_BE_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_BE_CLK_EDGE_MASK		(0x00080000)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_BE_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_BE_CLK_EDGE_SHIFT		(19)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_BE_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_BE_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_BE_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VDEB_SCALE_FE_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_FE_CLK_EDGE_MASK		(0x00040000)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_FE_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_FE_CLK_EDGE_SHIFT		(18)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_FE_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_FE_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_SCALE_FE_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VDEB_PROCESS2_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS2_CLK_EDGE_MASK		(0x00020000)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS2_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS2_CLK_EDGE_SHIFT		(17)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS2_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS2_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS2_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VDEB_PROCESS1_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS1_CLK_EDGE_MASK		(0x00010000)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS1_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS1_CLK_EDGE_SHIFT		(16)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS1_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS1_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_PROCESS1_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VDEB_ACCESS2_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS2_CLK_EDGE_MASK		(0x00008000)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS2_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS2_CLK_EDGE_SHIFT		(15)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS2_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS2_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS2_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VDEB_ACCESS1_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS1_CLK_EDGE_MASK		(0x00004000)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS1_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS1_CLK_EDGE_SHIFT		(14)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS1_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS1_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDEB_ACCESS1_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VDMC2_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC2_CLK_EDGE_MASK		(0x00002000)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC2_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC2_CLK_EDGE_SHIFT		(13)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC2_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC2_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC2_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VDMC1_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC1_CLK_EDGE_MASK		(0x00001000)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC1_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC1_CLK_EDGE_SHIFT		(12)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC1_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC1_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VDMC1_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VEC_ITRANS_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_ITRANS_CLK_EDGE_MASK		(0x00000800)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_ITRANS_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_ITRANS_CLK_EDGE_SHIFT		(11)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_ITRANS_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_ITRANS_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_ITRANS_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VEC_DEC_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_DEC_CLK_EDGE_MASK		(0x00000400)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_DEC_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_DEC_CLK_EDGE_SHIFT		(10)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_DEC_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_DEC_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_DEC_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VEC_BE_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_BE_CLK_EDGE_MASK		(0x00000200)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_BE_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_BE_CLK_EDGE_SHIFT		(9)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_BE_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_BE_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_BE_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VEC_REG_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_REG_CLK_EDGE_MASK		(0x00000100)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_REG_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_REG_CLK_EDGE_SHIFT		(8)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_REG_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_REG_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_REG_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VEC_FE_GRP2_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP2_CLK_EDGE_MASK		(0x00000080)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP2_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP2_CLK_EDGE_SHIFT		(7)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP2_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP2_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP2_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VEC_FE_GRP1_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP1_CLK_EDGE_MASK		(0x00000040)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP1_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP1_CLK_EDGE_SHIFT		(6)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP1_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP1_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_GRP1_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, VEC_FE_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_CLK_EDGE_MASK		(0x00000020)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_CLK_EDGE_SHIFT		(5)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_VEC_FE_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, MTX_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MTX_CLK_EDGE_MASK		(0x00000010)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MTX_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MTX_CLK_EDGE_SHIFT		(4)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MTX_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MTX_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MTX_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, REG_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_REG_CLK_EDGE_MASK		(0x00000008)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_REG_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_REG_CLK_EDGE_SHIFT		(3)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_REG_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_REG_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_REG_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, DMAC_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_DMAC_CLK_EDGE_MASK		(0x00000004)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_DMAC_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_DMAC_CLK_EDGE_SHIFT		(2)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_DMAC_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_DMAC_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_DMAC_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, MEM_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MEM_CLK_EDGE_MASK		(0x00000002)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MEM_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MEM_CLK_EDGE_SHIFT		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MEM_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MEM_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_MEM_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ENABLE_EDGE, CORE1_CLK_EDGE
*/
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_CORE1_CLK_EDGE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_CORE1_CLK_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_CORE1_CLK_EDGE_SHIFT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_CORE1_CLK_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_CORE1_CLK_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ENABLE_EDGE_CORE1_CLK_EDGE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_CLK_ERROR_CFG_OFFSET		(0x000C)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VDEB_SCALE_BE_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_BE_CLK_MONITOR_MASK		(0x00080000)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_BE_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_BE_CLK_MONITOR_SHIFT		(19)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_BE_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_BE_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_BE_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VDEB_SCALE_FE_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_FE_CLK_MONITOR_MASK		(0x00040000)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_FE_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_FE_CLK_MONITOR_SHIFT		(18)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_FE_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_FE_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_SCALE_FE_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VDEB_PROCESS2_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS2_CLK_MONITOR_MASK		(0x00020000)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS2_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS2_CLK_MONITOR_SHIFT		(17)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS2_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS2_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS2_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VDEB_PROCESS1_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS1_CLK_MONITOR_MASK		(0x00010000)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS1_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS1_CLK_MONITOR_SHIFT		(16)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS1_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS1_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_PROCESS1_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VDEB_ACCESS2_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS2_CLK_MONITOR_MASK		(0x00008000)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS2_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS2_CLK_MONITOR_SHIFT		(15)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS2_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS2_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS2_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VDEB_ACCESS1_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS1_CLK_MONITOR_MASK		(0x00004000)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS1_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS1_CLK_MONITOR_SHIFT		(14)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS1_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS1_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDEB_ACCESS1_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VDMC2_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC2_CLK_MONITOR_MASK		(0x00002000)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC2_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC2_CLK_MONITOR_SHIFT		(13)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC2_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC2_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC2_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VDMC1_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC1_CLK_MONITOR_MASK		(0x00001000)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC1_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC1_CLK_MONITOR_SHIFT		(12)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC1_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC1_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VDMC1_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VEC_ITRANS_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_ITRANS_CLK_MONITOR_MASK		(0x00000800)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_ITRANS_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_ITRANS_CLK_MONITOR_SHIFT		(11)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_ITRANS_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_ITRANS_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_ITRANS_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VEC_DEC_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_DEC_CLK_MONITOR_MASK		(0x00000400)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_DEC_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_DEC_CLK_MONITOR_SHIFT		(10)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_DEC_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_DEC_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_DEC_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VEC_BE_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_BE_CLK_MONITOR_MASK		(0x00000200)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_BE_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_BE_CLK_MONITOR_SHIFT		(9)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_BE_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_BE_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_BE_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VEC_REG_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_REG_CLK_MONITOR_MASK		(0x00000100)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_REG_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_REG_CLK_MONITOR_SHIFT		(8)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_REG_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_REG_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_REG_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VEC_FE_GRP2_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP2_CLK_MONITOR_MASK		(0x00000080)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP2_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP2_CLK_MONITOR_SHIFT		(7)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP2_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP2_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP2_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VEC_FE_GRP1_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP1_CLK_MONITOR_MASK		(0x00000040)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP1_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP1_CLK_MONITOR_SHIFT		(6)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP1_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP1_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_GRP1_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, VEC_FE_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_CLK_MONITOR_MASK		(0x00000020)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_CLK_MONITOR_SHIFT		(5)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_VEC_FE_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, MTX_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MTX_CLK_MONITOR_MASK		(0x00000010)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MTX_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MTX_CLK_MONITOR_SHIFT		(4)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MTX_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MTX_CLK_MONITOR_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MTX_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, REG_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_REG_CLK_MONITOR_MASK		(0x00000008)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_REG_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_REG_CLK_MONITOR_SHIFT		(3)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_REG_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_REG_CLK_MONITOR_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_REG_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, DMAC_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_DMAC_CLK_MONITOR_MASK		(0x00000004)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_DMAC_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_DMAC_CLK_MONITOR_SHIFT		(2)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_DMAC_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_DMAC_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_DMAC_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, MEM_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MEM_CLK_MONITOR_MASK		(0x00000002)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MEM_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MEM_CLK_MONITOR_SHIFT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MEM_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MEM_CLK_MONITOR_DEFAULT		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_MEM_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CLK_ERROR_CFG, CORE1_CLK_MONITOR
*/
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_CORE1_CLK_MONITOR_MASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_CORE1_CLK_MONITOR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_CORE1_CLK_MONITOR_SHIFT		(0)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_CORE1_CLK_MONITOR_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_CORE1_CLK_MONITOR_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_ERROR_CFG_CORE1_CLK_MONITOR_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_OFFSET		(0x00F0)

/* MSVDX_PIN_TEST, PERFORMANCE_COUNTER_CTRL, COUNTER_1_DIVIDER
*/
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DIVIDER_MASK		(0x00001C00)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DIVIDER_LSBMASK		(0x00000007)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DIVIDER_SHIFT		(10)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DIVIDER_LENGTH		(3)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DIVIDER_DEFAULT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DIVIDER_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, PERFORMANCE_COUNTER_CTRL, COUNTER_1_DOWN
*/
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DOWN_MASK		(0x00000200)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DOWN_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DOWN_SHIFT		(9)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DOWN_LENGTH		(1)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DOWN_DEFAULT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_DOWN_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, PERFORMANCE_COUNTER_CTRL, COUNTER_1_EN
*/
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_EN_MASK		(0x00000100)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_EN_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_EN_SHIFT		(8)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_EN_LENGTH		(1)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_EN_DEFAULT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_1_EN_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, PERFORMANCE_COUNTER_CTRL, COUNTER_0_DIVIDER
*/
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DIVIDER_MASK		(0x0000001C)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DIVIDER_LSBMASK		(0x00000007)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DIVIDER_SHIFT		(2)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DIVIDER_LENGTH		(3)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DIVIDER_DEFAULT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DIVIDER_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, PERFORMANCE_COUNTER_CTRL, COUNTER_0_DOWN
*/
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DOWN_MASK		(0x00000002)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DOWN_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DOWN_SHIFT		(1)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DOWN_LENGTH		(1)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DOWN_DEFAULT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_DOWN_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, PERFORMANCE_COUNTER_CTRL, COUNTER_0_EN
*/
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_EN_MASK		(0x00000001)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_EN_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_EN_SHIFT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_EN_LENGTH		(1)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_EN_DEFAULT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_CTRL_COUNTER_0_EN_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_0_OFFSET		(0x00F4)

/* MSVDX_PIN_TEST, PERFORMANCE_COUNTER_0, COUNTER_0_VALUE
*/
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_0_COUNTER_0_VALUE_MASK		(0xFFFFFFFF)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_0_COUNTER_0_VALUE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_0_COUNTER_0_VALUE_SHIFT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_0_COUNTER_0_VALUE_LENGTH		(32)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_0_COUNTER_0_VALUE_DEFAULT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_0_COUNTER_0_VALUE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_1_OFFSET		(0x00F8)

/* MSVDX_PIN_TEST, PERFORMANCE_COUNTER_1, COUNTER_1_VALUE
*/
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_1_COUNTER_1_VALUE_MASK		(0xFFFFFFFF)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_1_COUNTER_1_VALUE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_1_COUNTER_1_VALUE_SHIFT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_1_COUNTER_1_VALUE_LENGTH		(32)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_1_COUNTER_1_VALUE_DEFAULT		(0)
#define MSVDX_PIN_TEST_PERFORMANCE_COUNTER_1_COUNTER_1_VALUE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_CLK_EDGE_TEST_CONTROL_OFFSET		(0x0100)

/* MSVDX_PIN_TEST, CLK_EDGE_TEST_CONTROL, CLK_EDGE_DETECT_ENABLE
*/
#define MSVDX_PIN_TEST_CLK_EDGE_TEST_CONTROL_CLK_EDGE_DETECT_ENABLE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_EDGE_TEST_CONTROL_CLK_EDGE_DETECT_ENABLE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CLK_EDGE_TEST_CONTROL_CLK_EDGE_DETECT_ENABLE_SHIFT		(0)
#define MSVDX_PIN_TEST_CLK_EDGE_TEST_CONTROL_CLK_EDGE_DETECT_ENABLE_LENGTH		(1)
#define MSVDX_PIN_TEST_CLK_EDGE_TEST_CONTROL_CLK_EDGE_DETECT_ENABLE_DEFAULT		(0)
#define MSVDX_PIN_TEST_CLK_EDGE_TEST_CONTROL_CLK_EDGE_DETECT_ENABLE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_IRQ_EDGE_STATUS_OFFSET		(0x0110)

/* MSVDX_PIN_TEST, IRQ_EDGE_STATUS, MSVDX_IRQ_EDGE
*/
#define MSVDX_PIN_TEST_IRQ_EDGE_STATUS_MSVDX_IRQ_EDGE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_IRQ_EDGE_STATUS_MSVDX_IRQ_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_IRQ_EDGE_STATUS_MSVDX_IRQ_EDGE_SHIFT		(0)
#define MSVDX_PIN_TEST_IRQ_EDGE_STATUS_MSVDX_IRQ_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_IRQ_EDGE_STATUS_MSVDX_IRQ_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_IRQ_EDGE_STATUS_MSVDX_IRQ_EDGE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_EXT_DMAC_EDGE_STATUS_OFFSET		(0x0114)

/* MSVDX_PIN_TEST, EXT_DMAC_EDGE_STATUS, BITSTREAM_DREQ_EDGE
*/
#define MSVDX_PIN_TEST_EXT_DMAC_EDGE_STATUS_BITSTREAM_DREQ_EDGE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_EXT_DMAC_EDGE_STATUS_BITSTREAM_DREQ_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_EXT_DMAC_EDGE_STATUS_BITSTREAM_DREQ_EDGE_SHIFT		(0)
#define MSVDX_PIN_TEST_EXT_DMAC_EDGE_STATUS_BITSTREAM_DREQ_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_EXT_DMAC_EDGE_STATUS_BITSTREAM_DREQ_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_EXT_DMAC_EDGE_STATUS_BITSTREAM_DREQ_EDGE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_OFFSET		(0x011C)

/* MSVDX_PIN_TEST, CACHE_HINT_ERROR_STATUS, VDEB_CACHE_HINT_ERROR
*/
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDEB_CACHE_HINT_ERROR_MASK		(0x00000010)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDEB_CACHE_HINT_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDEB_CACHE_HINT_ERROR_SHIFT		(4)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDEB_CACHE_HINT_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDEB_CACHE_HINT_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDEB_CACHE_HINT_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CACHE_HINT_ERROR_STATUS, VDMC_CACHE_HINT_ERROR
*/
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDMC_CACHE_HINT_ERROR_MASK		(0x00000008)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDMC_CACHE_HINT_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDMC_CACHE_HINT_ERROR_SHIFT		(3)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDMC_CACHE_HINT_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDMC_CACHE_HINT_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VDMC_CACHE_HINT_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CACHE_HINT_ERROR_STATUS, VEC_CACHE_HINT_ERROR
*/
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VEC_CACHE_HINT_ERROR_MASK		(0x00000004)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VEC_CACHE_HINT_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VEC_CACHE_HINT_ERROR_SHIFT		(2)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VEC_CACHE_HINT_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VEC_CACHE_HINT_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_VEC_CACHE_HINT_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CACHE_HINT_ERROR_STATUS, DMAC_CACHE_HINT_ERROR
*/
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_DMAC_CACHE_HINT_ERROR_MASK		(0x00000002)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_DMAC_CACHE_HINT_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_DMAC_CACHE_HINT_ERROR_SHIFT		(1)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_DMAC_CACHE_HINT_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_DMAC_CACHE_HINT_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_DMAC_CACHE_HINT_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CACHE_HINT_ERROR_STATUS, BIF_CACHE_HINT_ERROR
*/
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_BIF_CACHE_HINT_ERROR_MASK		(0x00000001)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_BIF_CACHE_HINT_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_BIF_CACHE_HINT_ERROR_SHIFT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_BIF_CACHE_HINT_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_BIF_CACHE_HINT_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_STATUS_BIF_CACHE_HINT_ERROR_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_OFFSET		(0x0120)

/* MSVDX_PIN_TEST, CACHE_HINT_ERROR_CODE, ERROR_CACHE_HINT
*/
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_CACHE_HINT_MASK		(0x00000300)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_CACHE_HINT_LSBMASK		(0x00000003)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_CACHE_HINT_SHIFT		(8)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_CACHE_HINT_LENGTH		(2)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_CACHE_HINT_DEFAULT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_CACHE_HINT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, CACHE_HINT_ERROR_CODE, ERROR_TAG_SB
*/
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_TAG_SB_MASK		(0x0000000F)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_TAG_SB_LSBMASK		(0x0000000F)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_TAG_SB_SHIFT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_TAG_SB_LENGTH		(4)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_TAG_SB_DEFAULT		(0)
#define MSVDX_PIN_TEST_CACHE_HINT_ERROR_CODE_ERROR_TAG_SB_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_OFFSET		(0x0124)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, REQ_PRIORITY_EDGE
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_REQ_PRIORITY_EDGE_MASK		(0x01000000)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_REQ_PRIORITY_EDGE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_REQ_PRIORITY_EDGE_SHIFT		(24)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_REQ_PRIORITY_EDGE_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_REQ_PRIORITY_EDGE_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_REQ_PRIORITY_EDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VDEB_CMD_PRIORITY_CFG
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_CFG_MASK		(0x00100000)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_CFG_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_CFG_SHIFT		(20)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_CFG_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_CFG_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_CFG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VDMC_CMD_PRIORITY_CFG
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_CFG_MASK		(0x00080000)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_CFG_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_CFG_SHIFT		(19)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_CFG_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_CFG_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_CFG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VEC_CMD_PRIORITY_CFG
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_CFG_MASK		(0x00040000)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_CFG_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_CFG_SHIFT		(18)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_CFG_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_CFG_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_CFG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, DMAC_CMD_PRIORITY_CFG
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_CFG_MASK		(0x00020000)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_CFG_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_CFG_SHIFT		(17)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_CFG_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_CFG_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_CFG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, MMU_CMD_PRIORITY_CFG
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_CFG_MASK		(0x00010000)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_CFG_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_CFG_SHIFT		(16)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_CFG_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_CFG_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_CFG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VDEB_CMD_PRIORITY_ERROR
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_ERROR_MASK		(0x00001000)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_ERROR_SHIFT		(12)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VDMC_CMD_PRIORITY_ERROR
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_ERROR_MASK		(0x00000800)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_ERROR_SHIFT		(11)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VEC_CMD_PRIORITY_ERROR
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_ERROR_MASK		(0x00000400)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_ERROR_SHIFT		(10)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, DMAC_CMD_PRIORITY_ERROR
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_ERROR_MASK		(0x00000200)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_ERROR_SHIFT		(9)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, MMU_CMD_PRIORITY_ERROR
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_ERROR_MASK		(0x00000100)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_ERROR_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_ERROR_SHIFT		(8)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_ERROR_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_ERROR_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VDEB_CMD_PRIORITY
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_MASK		(0x00000010)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_SHIFT		(4)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDEB_CMD_PRIORITY_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VDMC_CMD_PRIORITY
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_MASK		(0x00000008)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_SHIFT		(3)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VDMC_CMD_PRIORITY_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, VEC_CMD_PRIORITY
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_MASK		(0x00000004)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_SHIFT		(2)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_VEC_CMD_PRIORITY_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, DMAC_CMD_PRIORITY
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_MASK		(0x00000002)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_SHIFT		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_DMAC_CMD_PRIORITY_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, MEM_PRIORITY_STATUS, MMU_CMD_PRIORITY
*/
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_MASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_SHIFT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_PRIORITY_STATUS_MMU_CMD_PRIORITY_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_MEM_LIMITED_CTRL_OFFSET		(0x0128)

/* MSVDX_PIN_TEST, MEM_LIMITED_CTRL, MEM_LIMITED_ENABLE
*/
#define MSVDX_PIN_TEST_MEM_LIMITED_CTRL_MEM_LIMITED_ENABLE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_LIMITED_CTRL_MEM_LIMITED_ENABLE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_MEM_LIMITED_CTRL_MEM_LIMITED_ENABLE_SHIFT		(0)
#define MSVDX_PIN_TEST_MEM_LIMITED_CTRL_MEM_LIMITED_ENABLE_LENGTH		(1)
#define MSVDX_PIN_TEST_MEM_LIMITED_CTRL_MEM_LIMITED_ENABLE_DEFAULT		(0)
#define MSVDX_PIN_TEST_MEM_LIMITED_CTRL_MEM_LIMITED_ENABLE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_FUSE_CONTROL_OFFSET		(0x0130)

/* MSVDX_PIN_TEST, FUSE_CONTROL, HD_SUPPORTED
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_HD_SUPPORTED_MASK		(0x00000800)
#define MSVDX_PIN_TEST_FUSE_CONTROL_HD_SUPPORTED_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_HD_SUPPORTED_SHIFT		(11)
#define MSVDX_PIN_TEST_FUSE_CONTROL_HD_SUPPORTED_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_HD_SUPPORTED_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_HD_SUPPORTED_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, VP8_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP8_FUSE_MASK		(0x00000400)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP8_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP8_FUSE_SHIFT		(10)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP8_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP8_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP8_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, VP6_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP6_FUSE_MASK		(0x00000200)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP6_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP6_FUSE_SHIFT		(9)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP6_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP6_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VP6_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, RV_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_RV_FUSE_MASK		(0x00000100)
#define MSVDX_PIN_TEST_FUSE_CONTROL_RV_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_RV_FUSE_SHIFT		(8)
#define MSVDX_PIN_TEST_FUSE_CONTROL_RV_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_RV_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_RV_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, SORENSON_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_SORENSON_FUSE_MASK		(0x00000080)
#define MSVDX_PIN_TEST_FUSE_CONTROL_SORENSON_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_SORENSON_FUSE_SHIFT		(7)
#define MSVDX_PIN_TEST_FUSE_CONTROL_SORENSON_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_SORENSON_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_SORENSON_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, AVS_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_AVS_FUSE_MASK		(0x00000040)
#define MSVDX_PIN_TEST_FUSE_CONTROL_AVS_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_AVS_FUSE_SHIFT		(6)
#define MSVDX_PIN_TEST_FUSE_CONTROL_AVS_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_AVS_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_AVS_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, MPEG4_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG4_FUSE_MASK		(0x00000020)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG4_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG4_FUSE_SHIFT		(5)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG4_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG4_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG4_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, MPEG2_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG2_FUSE_MASK		(0x00000010)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG2_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG2_FUSE_SHIFT		(4)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG2_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG2_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG2_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, MPEG1_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG1_FUSE_MASK		(0x00000008)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG1_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG1_FUSE_SHIFT		(3)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG1_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG1_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_MPEG1_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, WMV9_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_WMV9_FUSE_MASK		(0x00000004)
#define MSVDX_PIN_TEST_FUSE_CONTROL_WMV9_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_WMV9_FUSE_SHIFT		(2)
#define MSVDX_PIN_TEST_FUSE_CONTROL_WMV9_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_WMV9_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_WMV9_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, VC1_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_VC1_FUSE_MASK		(0x00000002)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VC1_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VC1_FUSE_SHIFT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VC1_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VC1_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_VC1_FUSE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, FUSE_CONTROL, H264_FUSE
*/
#define MSVDX_PIN_TEST_FUSE_CONTROL_H264_FUSE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_H264_FUSE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_FUSE_CONTROL_H264_FUSE_SHIFT		(0)
#define MSVDX_PIN_TEST_FUSE_CONTROL_H264_FUSE_LENGTH		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_H264_FUSE_DEFAULT		(1)
#define MSVDX_PIN_TEST_FUSE_CONTROL_H264_FUSE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_STREAM_COUNTER_STATUS_OFFSET		(0x0134)

/* MSVDX_PIN_TEST, STREAM_COUNTER_STATUS, STREAM_COUNTER_CAPTURE
*/
#define MSVDX_PIN_TEST_STREAM_COUNTER_STATUS_STREAM_COUNTER_CAPTURE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_STREAM_COUNTER_STATUS_STREAM_COUNTER_CAPTURE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_STREAM_COUNTER_STATUS_STREAM_COUNTER_CAPTURE_SHIFT		(0)
#define MSVDX_PIN_TEST_STREAM_COUNTER_STATUS_STREAM_COUNTER_CAPTURE_LENGTH		(1)
#define MSVDX_PIN_TEST_STREAM_COUNTER_STATUS_STREAM_COUNTER_CAPTURE_DEFAULT		(0)
#define MSVDX_PIN_TEST_STREAM_COUNTER_STATUS_STREAM_COUNTER_CAPTURE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_STREAM_ID_VALUE_OFFSET		(0x0138)

/* MSVDX_PIN_TEST, STREAM_ID_VALUE, CAPTURED_STREAM_ID
*/
#define MSVDX_PIN_TEST_STREAM_ID_VALUE_CAPTURED_STREAM_ID_MASK		(0x000000FF)
#define MSVDX_PIN_TEST_STREAM_ID_VALUE_CAPTURED_STREAM_ID_LSBMASK		(0x000000FF)
#define MSVDX_PIN_TEST_STREAM_ID_VALUE_CAPTURED_STREAM_ID_SHIFT		(0)
#define MSVDX_PIN_TEST_STREAM_ID_VALUE_CAPTURED_STREAM_ID_LENGTH		(8)
#define MSVDX_PIN_TEST_STREAM_ID_VALUE_CAPTURED_STREAM_ID_DEFAULT		(0)
#define MSVDX_PIN_TEST_STREAM_ID_VALUE_CAPTURED_STREAM_ID_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_STREAM_COUNTER_VALUE_OFFSET		(0x013C)

/* MSVDX_PIN_TEST, STREAM_COUNTER_VALUE, CAPTURED_STREAM_COUNTER
*/
#define MSVDX_PIN_TEST_STREAM_COUNTER_VALUE_CAPTURED_STREAM_COUNTER_MASK		(0xFFFFFFFF)
#define MSVDX_PIN_TEST_STREAM_COUNTER_VALUE_CAPTURED_STREAM_COUNTER_LSBMASK		(0xFFFFFFFF)
#define MSVDX_PIN_TEST_STREAM_COUNTER_VALUE_CAPTURED_STREAM_COUNTER_SHIFT		(0)
#define MSVDX_PIN_TEST_STREAM_COUNTER_VALUE_CAPTURED_STREAM_COUNTER_LENGTH		(32)
#define MSVDX_PIN_TEST_STREAM_COUNTER_VALUE_CAPTURED_STREAM_COUNTER_DEFAULT		(0)
#define MSVDX_PIN_TEST_STREAM_COUNTER_VALUE_CAPTURED_STREAM_COUNTER_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_DESIGNER_FIELD1_CONTROL_OFFSET		(0x0140)

/* MSVDX_PIN_TEST, DESIGNER_FIELD1_CONTROL, DESIGNER_FIELD1_VALUE
*/
#define MSVDX_PIN_TEST_DESIGNER_FIELD1_CONTROL_DESIGNER_FIELD1_VALUE_MASK		(0x0000FFFF)
#define MSVDX_PIN_TEST_DESIGNER_FIELD1_CONTROL_DESIGNER_FIELD1_VALUE_LSBMASK		(0x0000FFFF)
#define MSVDX_PIN_TEST_DESIGNER_FIELD1_CONTROL_DESIGNER_FIELD1_VALUE_SHIFT		(0)
#define MSVDX_PIN_TEST_DESIGNER_FIELD1_CONTROL_DESIGNER_FIELD1_VALUE_LENGTH		(16)
#define MSVDX_PIN_TEST_DESIGNER_FIELD1_CONTROL_DESIGNER_FIELD1_VALUE_DEFAULT		(0)
#define MSVDX_PIN_TEST_DESIGNER_FIELD1_CONTROL_DESIGNER_FIELD1_VALUE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_OFFSET		(0x0144)

/* MSVDX_PIN_TEST, RTM_OUTPUT_TEST, RTM_OUTPUT_B_TEST
*/
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_B_TEST_MASK		(0x0000FF00)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_B_TEST_LSBMASK		(0x000000FF)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_B_TEST_SHIFT		(8)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_B_TEST_LENGTH		(8)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_B_TEST_DEFAULT		(0)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_B_TEST_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_PIN_TEST, RTM_OUTPUT_TEST, RTM_OUTPUT_A_TEST
*/
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_A_TEST_MASK		(0x000000FF)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_A_TEST_LSBMASK		(0x000000FF)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_A_TEST_SHIFT		(0)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_A_TEST_LENGTH		(8)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_A_TEST_DEFAULT		(0)
#define MSVDX_PIN_TEST_RTM_OUTPUT_TEST_RTM_OUTPUT_A_TEST_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_PIN_TEST_TRUSTED_HOST_CONTROL_OFFSET		(0x0148)

/* MSVDX_PIN_TEST, TRUSTED_HOST_CONTROL, TRUSTED_HOST_VALUE
*/
#define MSVDX_PIN_TEST_TRUSTED_HOST_CONTROL_TRUSTED_HOST_VALUE_MASK		(0x00000001)
#define MSVDX_PIN_TEST_TRUSTED_HOST_CONTROL_TRUSTED_HOST_VALUE_LSBMASK		(0x00000001)
#define MSVDX_PIN_TEST_TRUSTED_HOST_CONTROL_TRUSTED_HOST_VALUE_SHIFT		(0)
#define MSVDX_PIN_TEST_TRUSTED_HOST_CONTROL_TRUSTED_HOST_VALUE_LENGTH		(1)
#define MSVDX_PIN_TEST_TRUSTED_HOST_CONTROL_TRUSTED_HOST_VALUE_DEFAULT		(0)
#define MSVDX_PIN_TEST_TRUSTED_HOST_CONTROL_TRUSTED_HOST_VALUE_SIGNED_FIELD	(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_PIN_TEST_REGS_H__ */
