/*!
 *****************************************************************************
 *
 * @File       msvdx_vdeb_reg_io2.h
 * @Description    This file contains the MSVDX_VDEB_REG_IO2_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__MSVDX_VDEB_REG_IO2_H__)
#define __MSVDX_VDEB_REG_IO2_H__

#ifdef __cplusplus
extern "C" {
#endif


#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_OFFSET		(0x0000)

/* MSVDX_VDEB, CR_VDEB_OPERATING_MODE, CR_VDEB_SCALE_AUTO_RESTART_DISABLE
*/
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_SCALE_AUTO_RESTART_DISABLE_MASK		(0x00000040)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_SCALE_AUTO_RESTART_DISABLE_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_SCALE_AUTO_RESTART_DISABLE_SHIFT		(6)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_SCALE_AUTO_RESTART_DISABLE_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_SCALE_AUTO_RESTART_DISABLE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_SCALE_AUTO_RESTART_DISABLE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_OPERATING_MODE, CR_VDEB_BB_DISABLE_B4WRITE
*/
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4WRITE_MASK		(0x00000020)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4WRITE_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4WRITE_SHIFT		(5)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4WRITE_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4WRITE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4WRITE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_OPERATING_MODE, CR_VDEB_BB_DISABLE_B4READ
*/
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4READ_MASK		(0x00000010)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4READ_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4READ_SHIFT		(4)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4READ_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4READ_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_BB_DISABLE_B4READ_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_OPERATING_MODE, CR_VDEB_VC1_ERR_BIAS_ABOVE
*/
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_ERR_BIAS_ABOVE_MASK		(0x00000004)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_ERR_BIAS_ABOVE_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_ERR_BIAS_ABOVE_SHIFT		(2)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_ERR_BIAS_ABOVE_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_ERR_BIAS_ABOVE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_ERR_BIAS_ABOVE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_OPERATING_MODE, CR_VDEB_VC1_BIAS_IN_HOST
*/
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_BIAS_IN_HOST_MASK		(0x00000002)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_BIAS_IN_HOST_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_BIAS_IN_HOST_SHIFT		(1)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_BIAS_IN_HOST_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_BIAS_IN_HOST_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_BIAS_IN_HOST_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_OPERATING_MODE, CR_VDEB_VC1_INLOOP_BOUNDARY
*/
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_INLOOP_BOUNDARY_MASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_INLOOP_BOUNDARY_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_INLOOP_BOUNDARY_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_INLOOP_BOUNDARY_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_INLOOP_BOUNDARY_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_OPERATING_MODE_CR_VDEB_VC1_INLOOP_BOUNDARY_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_OFFSET		(0x0004)

/* MSVDX_VDEB, CR_VDEB_PREFETCH_FIFO, CR_VDEB_PREFETCH_FIFO_DISABLED
*/
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_DISABLED_MASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_DISABLED_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_DISABLED_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_DISABLED_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_DISABLED_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_DISABLED_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PREFETCH_FIFO, CR_VDEB_PREFETCH_FIFO_REQUESTS
*/
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_REQUESTS_MASK		(0x003F0000)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_REQUESTS_LSBMASK		(0x0000003F)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_REQUESTS_SHIFT		(16)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_REQUESTS_LENGTH		(6)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_REQUESTS_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_REQUESTS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PREFETCH_FIFO, CR_VDEB_PREFETCH_FIFO_SPACE
*/
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_SPACE_MASK		(0x7F000000)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_SPACE_LSBMASK		(0x0000007F)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_SPACE_SHIFT		(24)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_SPACE_LENGTH		(7)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_SPACE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PREFETCH_FIFO_CR_VDEB_PREFETCH_FIFO_SPACE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_OFFSET		(0x000C)

/* MSVDX_VDEB, CR_VDEB_SYS_MEM_RDATA_SIGNATURE, CR_VDEB_SYS_MEM_RDATA_SIGNATURE
*/
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_CR_VDEB_SYS_MEM_RDATA_SIGNATURE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_OFFSET		(0x0010)

/* MSVDX_VDEB, CR_VDEB_SYS_MEM_ADDR_SIGNATURE, CR_VDEB_SYS_MEM_ADDR_SIGNATURE
*/
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_CR_VDEB_SYS_MEM_ADDR_SIGNATURE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_OFFSET		(0x0014)

/* MSVDX_VDEB, CR_VDEB_SYS_MEM_WDATA_SIGNATURE, CR_VDEB_SYS_MEM_WDATA_SIGNATURE
*/
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_CR_VDEB_SYS_MEM_WDATA_SIGNATURE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_OFFSET		(0x0018)

/* MSVDX_VDEB, CR_VDEB_VIRTUAL_FIFO_CONTROL, CR_VDEB_VF_ENABLED
*/
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_ENABLED_MASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_ENABLED_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_ENABLED_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_ENABLED_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_ENABLED_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_ENABLED_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_VIRTUAL_FIFO_CONTROL, CR_VDEB_VF_FLOWRATE_MUL
*/
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_MUL_MASK		(0x000000F0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_MUL_LSBMASK		(0x0000000F)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_MUL_SHIFT		(4)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_MUL_LENGTH		(4)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_MUL_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_MUL_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_VIRTUAL_FIFO_CONTROL, CR_VDEB_VF_FLOWRATE_DIV
*/
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_DIV_MASK		(0x0000FF00)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_DIV_LSBMASK		(0x000000FF)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_DIV_SHIFT		(8)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_DIV_LENGTH		(8)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_DIV_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_FLOWRATE_DIV_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_VIRTUAL_FIFO_CONTROL, CR_VDEB_VF_MIN_METRIC
*/
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_MIN_METRIC_MASK		(0x00FF0000)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_MIN_METRIC_LSBMASK		(0x000000FF)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_MIN_METRIC_SHIFT		(16)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_MIN_METRIC_LENGTH		(8)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_MIN_METRIC_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_CONTROL_CR_VDEB_VF_MIN_METRIC_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_OFFSET		(0x001C)

/* MSVDX_VDEB, CR_VDEB_VIRTUAL_FIFO_ACCUM, CR_VDEB_VF_MIN_ACC
*/
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MIN_ACC_MASK		(0x00000FFF)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MIN_ACC_LSBMASK		(0x00000FFF)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MIN_ACC_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MIN_ACC_LENGTH		(12)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MIN_ACC_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MIN_ACC_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_VIRTUAL_FIFO_ACCUM, CR_VDEB_VF_MAX_ACC
*/
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MAX_ACC_MASK		(0x00FFF000)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MAX_ACC_LSBMASK		(0x00000FFF)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MAX_ACC_SHIFT		(12)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MAX_ACC_LENGTH		(12)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MAX_ACC_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_VIRTUAL_FIFO_ACCUM_CR_VDEB_VF_MAX_ACC_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_OFFSET		(0x0020)

/* MSVDX_VDEB, CR_VDEB_RECON_BUF_STATUS, CR_VDEB_RECON_BUF_MB_ERROR
*/
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_ERROR_MASK		(0x01000000)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_ERROR_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_ERROR_SHIFT		(24)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_ERROR_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_ERROR_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_RECON_BUF_STATUS, CR_VDEB_RECON_BUF_RD_STATE
*/
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_STATE_MASK		(0x00C00000)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_STATE_LSBMASK		(0x00000003)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_STATE_SHIFT		(22)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_STATE_LENGTH		(2)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_STATE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_STATE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_RECON_BUF_STATUS, CR_VDEB_RECON_BUF_RD_PTR
*/
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_PTR_MASK		(0x00380000)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_PTR_LSBMASK		(0x00000007)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_PTR_SHIFT		(19)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_PTR_LENGTH		(3)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_PTR_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_RD_PTR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_RECON_BUF_STATUS, CR_VDEB_RECON_BUF_WR_PTR
*/
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_WR_PTR_MASK		(0x00070000)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_WR_PTR_LSBMASK		(0x00000007)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_WR_PTR_SHIFT		(16)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_WR_PTR_LENGTH		(3)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_WR_PTR_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_WR_PTR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_RECON_BUF_STATUS, CR_VDEB_RECON_BUF_MB_NO_Y
*/
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_Y_MASK		(0x0000FF00)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_Y_LSBMASK		(0x000000FF)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_Y_SHIFT		(8)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_Y_LENGTH		(8)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_Y_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_Y_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_RECON_BUF_STATUS, CR_VDEB_RECON_BUF_MB_NO_X
*/
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_X_MASK		(0x000000FF)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_X_LSBMASK		(0x000000FF)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_X_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_X_LENGTH		(8)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_X_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_RECON_BUF_STATUS_CR_VDEB_RECON_BUF_MB_NO_X_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_OFFSET		(0x0024)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_SLICE_FLUSH
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_SLICE_FLUSH_MASK		(0x20000000)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_SLICE_FLUSH_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_SLICE_FLUSH_SHIFT		(29)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_SLICE_FLUSH_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_SLICE_FLUSH_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_SLICE_FLUSH_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_MB_EOP
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOP_MASK		(0x10000000)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOP_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOP_SHIFT		(28)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOP_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOP_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_MB_EOS
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOS_MASK		(0x08000000)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOS_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOS_SHIFT		(27)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOS_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOS_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_EOS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_MB_WR_PTR
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_WR_PTR_MASK		(0x07000000)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_WR_PTR_LSBMASK		(0x00000007)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_WR_PTR_SHIFT		(24)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_WR_PTR_LENGTH		(3)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_WR_PTR_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_WR_PTR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_MB_RD_PTR
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_RD_PTR_MASK		(0x00E00000)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_RD_PTR_LSBMASK		(0x00000007)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_RD_PTR_SHIFT		(21)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_RD_PTR_LENGTH		(3)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_RD_PTR_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_RD_PTR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_MB_AVAILABLE
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_AVAILABLE_MASK		(0x00100000)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_AVAILABLE_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_AVAILABLE_SHIFT		(20)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_AVAILABLE_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_AVAILABLE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_AVAILABLE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_FLUSH_AVAILABLE
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_AVAILABLE_MASK		(0x00080000)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_AVAILABLE_LSBMASK		(0x00000001)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_AVAILABLE_SHIFT		(19)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_AVAILABLE_LENGTH		(1)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_AVAILABLE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_AVAILABLE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_FLUSH_STATE
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_STATE_MASK		(0x00070000)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_STATE_LSBMASK		(0x00000007)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_STATE_SHIFT		(16)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_STATE_LENGTH		(3)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_STATE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_FLUSH_STATE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_MB_NO_Y
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_Y_MASK		(0x0000FF00)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_Y_LSBMASK		(0x000000FF)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_Y_SHIFT		(8)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_Y_LENGTH		(8)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_Y_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_Y_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VDEB, CR_VDEB_PARAMS_STORE_STATUS, CR_VDEB_PARAMS_STORE_MB_NO_X
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_X_MASK		(0x000000FF)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_X_LSBMASK		(0x000000FF)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_X_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_X_LENGTH		(8)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_X_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_STORE_STATUS_CR_VDEB_PARAMS_STORE_MB_NO_X_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_SLICE_INTERRUPT_COUNT_OFFSET		(0x0028)

/* MSVDX_VDEB, CR_VDEB_SLICE_INTERRUPT_COUNT, CR_VDEB_SLICE_INTERRUPT_COUNT
*/
#define MSVDX_VDEB_CR_VDEB_SLICE_INTERRUPT_COUNT_CR_VDEB_SLICE_INTERRUPT_COUNT_MASK		(0x00000007)
#define MSVDX_VDEB_CR_VDEB_SLICE_INTERRUPT_COUNT_CR_VDEB_SLICE_INTERRUPT_COUNT_LSBMASK		(0x00000007)
#define MSVDX_VDEB_CR_VDEB_SLICE_INTERRUPT_COUNT_CR_VDEB_SLICE_INTERRUPT_COUNT_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_SLICE_INTERRUPT_COUNT_CR_VDEB_SLICE_INTERRUPT_COUNT_LENGTH		(3)
#define MSVDX_VDEB_CR_VDEB_SLICE_INTERRUPT_COUNT_CR_VDEB_SLICE_INTERRUPT_COUNT_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_SLICE_INTERRUPT_COUNT_CR_VDEB_SLICE_INTERRUPT_COUNT_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_OFFSET		(0x0030)

/* MSVDX_VDEB, CR_VDEB_BLOCK_MEM_DIAGNOSTICS, CR_VDEB_BLOCK_MEM_DIAGNOSTICS
*/
#define MSVDX_VDEB_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_CR_VDEB_BLOCK_MEM_DIAGNOSTICS_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_PARAMS_DIAGNOSTICS_OFFSET		(0x0034)

/* MSVDX_VDEB, CR_VDEB_PARAMS_DIAGNOSTICS, CR_VDEB_PARAMS_DIAGNOSTICS
*/
#define MSVDX_VDEB_CR_VDEB_PARAMS_DIAGNOSTICS_CR_VDEB_PARAMS_DIAGNOSTICS_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_PARAMS_DIAGNOSTICS_CR_VDEB_PARAMS_DIAGNOSTICS_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_PARAMS_DIAGNOSTICS_CR_VDEB_PARAMS_DIAGNOSTICS_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_DIAGNOSTICS_CR_VDEB_PARAMS_DIAGNOSTICS_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_PARAMS_DIAGNOSTICS_CR_VDEB_PARAMS_DIAGNOSTICS_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_PARAMS_DIAGNOSTICS_CR_VDEB_PARAMS_DIAGNOSTICS_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_FILTER_DIAGNOSTICS_OFFSET		(0x0038)

/* MSVDX_VDEB, CR_VDEB_FILTER_DIAGNOSTICS, CR_VDEB_FILTER_DIAGNOSTICS
*/
#define MSVDX_VDEB_CR_VDEB_FILTER_DIAGNOSTICS_CR_VDEB_FILTER_DIAGNOSTICS_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_FILTER_DIAGNOSTICS_CR_VDEB_FILTER_DIAGNOSTICS_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_FILTER_DIAGNOSTICS_CR_VDEB_FILTER_DIAGNOSTICS_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_FILTER_DIAGNOSTICS_CR_VDEB_FILTER_DIAGNOSTICS_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_FILTER_DIAGNOSTICS_CR_VDEB_FILTER_DIAGNOSTICS_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_FILTER_DIAGNOSTICS_CR_VDEB_FILTER_DIAGNOSTICS_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_MAIN_DIAGNOSTICS_OFFSET		(0x003C)

/* MSVDX_VDEB, CR_VDEB_MAIN_DIAGNOSTICS, CR_VDEB_MAIN_DIAGNOSTICS
*/
#define MSVDX_VDEB_CR_VDEB_MAIN_DIAGNOSTICS_CR_VDEB_MAIN_DIAGNOSTICS_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_MAIN_DIAGNOSTICS_CR_VDEB_MAIN_DIAGNOSTICS_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_MAIN_DIAGNOSTICS_CR_VDEB_MAIN_DIAGNOSTICS_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_MAIN_DIAGNOSTICS_CR_VDEB_MAIN_DIAGNOSTICS_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_MAIN_DIAGNOSTICS_CR_VDEB_MAIN_DIAGNOSTICS_DEFAULT		(45056)
#define MSVDX_VDEB_CR_VDEB_MAIN_DIAGNOSTICS_CR_VDEB_MAIN_DIAGNOSTICS_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_BURSTB_ADDR_SIGNATURE_OFFSET		(0x0040)

/* MSVDX_VDEB, CR_VDEB_BURSTB_ADDR_SIGNATURE, CR_VDEB_BURSTB_ADDR_SIGNATURE
*/
#define MSVDX_VDEB_CR_VDEB_BURSTB_ADDR_SIGNATURE_CR_VDEB_BURSTB_ADDR_SIGNATURE_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_BURSTB_ADDR_SIGNATURE_CR_VDEB_BURSTB_ADDR_SIGNATURE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_BURSTB_ADDR_SIGNATURE_CR_VDEB_BURSTB_ADDR_SIGNATURE_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_BURSTB_ADDR_SIGNATURE_CR_VDEB_BURSTB_ADDR_SIGNATURE_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_BURSTB_ADDR_SIGNATURE_CR_VDEB_BURSTB_ADDR_SIGNATURE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_BURSTB_ADDR_SIGNATURE_CR_VDEB_BURSTB_ADDR_SIGNATURE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_BURSTB_WDATA_SIGNATURE_OFFSET		(0x0044)

/* MSVDX_VDEB, CR_VDEB_BURSTB_WDATA_SIGNATURE, CR_VDEB_BURSTB_WDATA_SIGNATURE
*/
#define MSVDX_VDEB_CR_VDEB_BURSTB_WDATA_SIGNATURE_CR_VDEB_BURSTB_WDATA_SIGNATURE_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_BURSTB_WDATA_SIGNATURE_CR_VDEB_BURSTB_WDATA_SIGNATURE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_BURSTB_WDATA_SIGNATURE_CR_VDEB_BURSTB_WDATA_SIGNATURE_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_BURSTB_WDATA_SIGNATURE_CR_VDEB_BURSTB_WDATA_SIGNATURE_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_BURSTB_WDATA_SIGNATURE_CR_VDEB_BURSTB_WDATA_SIGNATURE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_BURSTB_WDATA_SIGNATURE_CR_VDEB_BURSTB_WDATA_SIGNATURE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_SCALE_ADDR_SIGNATURE_OFFSET		(0x0048)

/* MSVDX_VDEB, CR_VDEB_SCALE_ADDR_SIGNATURE, CR_VDEB_SCALE_ADDR_SIGNATURE
*/
#define MSVDX_VDEB_CR_VDEB_SCALE_ADDR_SIGNATURE_CR_VDEB_SCALE_ADDR_SIGNATURE_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SCALE_ADDR_SIGNATURE_CR_VDEB_SCALE_ADDR_SIGNATURE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SCALE_ADDR_SIGNATURE_CR_VDEB_SCALE_ADDR_SIGNATURE_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_SCALE_ADDR_SIGNATURE_CR_VDEB_SCALE_ADDR_SIGNATURE_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_SCALE_ADDR_SIGNATURE_CR_VDEB_SCALE_ADDR_SIGNATURE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_SCALE_ADDR_SIGNATURE_CR_VDEB_SCALE_ADDR_SIGNATURE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VDEB_CR_VDEB_SCALE_WDATA_SIGNATURE_OFFSET		(0x004C)

/* MSVDX_VDEB, CR_VDEB_SCALE_WDATA_SIGNATURE, CR_VDEB_SCALE_WDATA_SIGNATURE
*/
#define MSVDX_VDEB_CR_VDEB_SCALE_WDATA_SIGNATURE_CR_VDEB_SCALE_WDATA_SIGNATURE_MASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SCALE_WDATA_SIGNATURE_CR_VDEB_SCALE_WDATA_SIGNATURE_LSBMASK		(0xFFFFFFFF)
#define MSVDX_VDEB_CR_VDEB_SCALE_WDATA_SIGNATURE_CR_VDEB_SCALE_WDATA_SIGNATURE_SHIFT		(0)
#define MSVDX_VDEB_CR_VDEB_SCALE_WDATA_SIGNATURE_CR_VDEB_SCALE_WDATA_SIGNATURE_LENGTH		(32)
#define MSVDX_VDEB_CR_VDEB_SCALE_WDATA_SIGNATURE_CR_VDEB_SCALE_WDATA_SIGNATURE_DEFAULT		(0)
#define MSVDX_VDEB_CR_VDEB_SCALE_WDATA_SIGNATURE_CR_VDEB_SCALE_WDATA_SIGNATURE_SIGNED_FIELD	(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_VDEB_REG_IO2_H__ */
