/*!
 *****************************************************************************
 *
 * @File       vdecfw_msg_mem_io.h
 * @Description    This file contains the VDECFW_MSG_MEM_IO_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__VDECFW_MSG_MEM_IO_H__)
#define __VDECFW_MSG_MEM_IO_H__

#ifdef __cplusplus
extern "C" {
#endif


#define V2_PADMSG_SIZE		(4)

// V2_PADMSG     SIZE
#define V2_PADMSG_SIZE_START_BIT		0
#define V2_PADMSG_SIZE_END_BIT		7
#define V2_PADMSG_SIZE_ALIGNMENT		(1)
#define V2_PADMSG_SIZE_TYPE		IMG_UINT8
#define V2_PADMSG_SIZE_MASK		(0xFF)
#define V2_PADMSG_SIZE_LSBMASK		(0xFF)
#define V2_PADMSG_SIZE_OFFSET		(0x0000)
#define V2_PADMSG_SIZE_SHIFT		(0)
#define V2_PADMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_PADMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_PADMSG     MID
#define V2_PADMSG_MID_START_BIT		8
#define V2_PADMSG_MID_END_BIT		15
#define V2_PADMSG_MID_ALIGNMENT		(1)
#define V2_PADMSG_MID_TYPE		IMG_UINT8
#define V2_PADMSG_MID_MASK		(0xFF)
#define V2_PADMSG_MID_LSBMASK		(0xFF)
#define V2_PADMSG_MID_OFFSET		(0x0001)
#define V2_PADMSG_MID_SHIFT		(0)
#define V2_PADMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_PADMSG_MID_TRUSTED		(IMG_FALSE)

// V2_PADMSG     TYPE
#define V2_PADMSG_TYPE_START_BIT		16
#define V2_PADMSG_TYPE_END_BIT		23
#define V2_PADMSG_TYPE_ALIGNMENT		(1)
#define V2_PADMSG_TYPE_TYPE		IMG_UINT8
#define V2_PADMSG_TYPE_MASK		(0xFF)
#define V2_PADMSG_TYPE_LSBMASK		(0xFF)
#define V2_PADMSG_TYPE_OFFSET		(0x0002)
#define V2_PADMSG_TYPE_SHIFT		(0)
#define V2_PADMSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define V2_PADMSG_TYPE_TRUSTED		(IMG_FALSE)

// V2_PADMSG     FENCE_ID
#define V2_PADMSG_FENCE_ID_START_BIT		24
#define V2_PADMSG_FENCE_ID_END_BIT		31
#define V2_PADMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_PADMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_PADMSG_FENCE_ID_MASK		(0xFF)
#define V2_PADMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_PADMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_PADMSG_FENCE_ID_SHIFT		(0)
#define V2_PADMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_PADMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

#define V2_INITMSG_SIZE		(156)

// V2_INITMSG     MMU_DIR_LIST_BASE
#define V2_INITMSG_MMU_DIR_LIST_BASE_START_BIT		0
#define V2_INITMSG_MMU_DIR_LIST_BASE_END_BIT		31
#define V2_INITMSG_MMU_DIR_LIST_BASE_ALIGNMENT		(4)
#define V2_INITMSG_MMU_DIR_LIST_BASE_TYPE		IMG_UINT32
#define V2_INITMSG_MMU_DIR_LIST_BASE_MASK		(0xFFFFFFFF)
#define V2_INITMSG_MMU_DIR_LIST_BASE_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_MMU_DIR_LIST_BASE_OFFSET		(0x0018)
#define V2_INITMSG_MMU_DIR_LIST_BASE_SHIFT		(0)
#define V2_INITMSG_MMU_DIR_LIST_BASE_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_MMU_DIR_LIST_BASE_STRIDE		(4)
#define V2_INITMSG_MMU_DIR_LIST_BASE_NO_ENTRIES		(4)
#define V2_INITMSG_MMU_DIR_LIST_BASE_TRUSTED		(IMG_FALSE)

// V2_INITMSG     MMU_TILE
#define V2_INITMSG_MMU_TILE_START_BIT		0
#define V2_INITMSG_MMU_TILE_END_BIT		31
#define V2_INITMSG_MMU_TILE_ALIGNMENT		(4)
#define V2_INITMSG_MMU_TILE_TYPE		IMG_UINT32
#define V2_INITMSG_MMU_TILE_MASK		(0xFFFFFFFF)
#define V2_INITMSG_MMU_TILE_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_MMU_TILE_OFFSET		(0x0030)
#define V2_INITMSG_MMU_TILE_SHIFT		(0)
#define V2_INITMSG_MMU_TILE_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_MMU_TILE_STRIDE		(4)
#define V2_INITMSG_MMU_TILE_NO_ENTRIES		(4)
#define V2_INITMSG_MMU_TILE_TRUSTED		(IMG_FALSE)

// V2_INITMSG     MMU_TILE_EXT
#define V2_INITMSG_MMU_TILE_EXT_START_BIT		0
#define V2_INITMSG_MMU_TILE_EXT_END_BIT		31
#define V2_INITMSG_MMU_TILE_EXT_ALIGNMENT		(4)
#define V2_INITMSG_MMU_TILE_EXT_TYPE		IMG_UINT32
#define V2_INITMSG_MMU_TILE_EXT_MASK		(0xFFFFFFFF)
#define V2_INITMSG_MMU_TILE_EXT_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_MMU_TILE_EXT_OFFSET		(0x0040)
#define V2_INITMSG_MMU_TILE_EXT_SHIFT		(0)
#define V2_INITMSG_MMU_TILE_EXT_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_MMU_TILE_EXT_STRIDE		(4)
#define V2_INITMSG_MMU_TILE_EXT_NO_ENTRIES		(4)
#define V2_INITMSG_MMU_TILE_EXT_TRUSTED		(IMG_FALSE)

// V2_INITMSG     RENDEC_INITIAL_CONTEXT
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_START_BIT		0
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_END_BIT		31
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_ALIGNMENT		(4)
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_TYPE		IMG_UINT32
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_MASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_OFFSET		(0x0080)
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_SHIFT		(0)
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_STRIDE		(4)
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_NO_ENTRIES		(6)
#define V2_INITMSG_RENDEC_INITIAL_CONTEXT_TRUSTED		(IMG_FALSE)

// V2_INITMSG     SIZE
#define V2_INITMSG_SIZE_START_BIT		0
#define V2_INITMSG_SIZE_END_BIT		7
#define V2_INITMSG_SIZE_ALIGNMENT		(1)
#define V2_INITMSG_SIZE_TYPE		IMG_UINT8
#define V2_INITMSG_SIZE_MASK		(0xFF)
#define V2_INITMSG_SIZE_LSBMASK		(0xFF)
#define V2_INITMSG_SIZE_OFFSET		(0x0000)
#define V2_INITMSG_SIZE_SHIFT		(0)
#define V2_INITMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_INITMSG     MID
#define V2_INITMSG_MID_START_BIT		8
#define V2_INITMSG_MID_END_BIT		15
#define V2_INITMSG_MID_ALIGNMENT		(1)
#define V2_INITMSG_MID_TYPE		IMG_UINT8
#define V2_INITMSG_MID_MASK		(0xFF)
#define V2_INITMSG_MID_LSBMASK		(0xFF)
#define V2_INITMSG_MID_OFFSET		(0x0001)
#define V2_INITMSG_MID_SHIFT		(0)
#define V2_INITMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_MID_TRUSTED		(IMG_FALSE)

// V2_INITMSG     TYPE
#define V2_INITMSG_TYPE_START_BIT		16
#define V2_INITMSG_TYPE_END_BIT		23
#define V2_INITMSG_TYPE_ALIGNMENT		(1)
#define V2_INITMSG_TYPE_TYPE		IMG_UINT8
#define V2_INITMSG_TYPE_MASK		(0xFF)
#define V2_INITMSG_TYPE_LSBMASK		(0xFF)
#define V2_INITMSG_TYPE_OFFSET		(0x0002)
#define V2_INITMSG_TYPE_SHIFT		(0)
#define V2_INITMSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_TYPE_TRUSTED		(IMG_FALSE)

// V2_INITMSG     FENCE_ID
#define V2_INITMSG_FENCE_ID_START_BIT		24
#define V2_INITMSG_FENCE_ID_END_BIT		31
#define V2_INITMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_INITMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_INITMSG_FENCE_ID_MASK		(0xFF)
#define V2_INITMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_INITMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_INITMSG_FENCE_ID_SHIFT		(0)
#define V2_INITMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_INITMSG     COREID
#define V2_INITMSG_COREID_START_BIT		0
#define V2_INITMSG_COREID_END_BIT		31
#define V2_INITMSG_COREID_ALIGNMENT		(4)
#define V2_INITMSG_COREID_TYPE		IMG_UINT32
#define V2_INITMSG_COREID_MASK		(0xFFFFFFFF)
#define V2_INITMSG_COREID_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_COREID_OFFSET		(0x0008)
#define V2_INITMSG_COREID_SHIFT		(0)
#define V2_INITMSG_COREID_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_COREID_TRUSTED		(IMG_FALSE)

// V2_INITMSG     PARSEONLY
#define V2_INITMSG_PARSEONLY_START_BIT		0
#define V2_INITMSG_PARSEONLY_END_BIT		0
#define V2_INITMSG_PARSEONLY_ALIGNMENT		(1)
#define V2_INITMSG_PARSEONLY_TYPE		IMG_UINT8
#define V2_INITMSG_PARSEONLY_MASK		(0x01)
#define V2_INITMSG_PARSEONLY_LSBMASK		(0x01)
#define V2_INITMSG_PARSEONLY_OFFSET		(0x0010)
#define V2_INITMSG_PARSEONLY_SHIFT		(0)
#define V2_INITMSG_PARSEONLY_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_PARSEONLY_TRUSTED		(IMG_FALSE)

// V2_INITMSG     FAKEBE
#define V2_INITMSG_FAKEBE_START_BIT		1
#define V2_INITMSG_FAKEBE_END_BIT		1
#define V2_INITMSG_FAKEBE_ALIGNMENT		(1)
#define V2_INITMSG_FAKEBE_TYPE		IMG_UINT8
#define V2_INITMSG_FAKEBE_MASK		(0x02)
#define V2_INITMSG_FAKEBE_LSBMASK		(0x01)
#define V2_INITMSG_FAKEBE_OFFSET		(0x0010)
#define V2_INITMSG_FAKEBE_SHIFT		(1)
#define V2_INITMSG_FAKEBE_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_FAKEBE_TRUSTED		(IMG_FALSE)

// V2_INITMSG     LOCKSTEP
#define V2_INITMSG_LOCKSTEP_START_BIT		2
#define V2_INITMSG_LOCKSTEP_END_BIT		2
#define V2_INITMSG_LOCKSTEP_ALIGNMENT		(1)
#define V2_INITMSG_LOCKSTEP_TYPE		IMG_UINT8
#define V2_INITMSG_LOCKSTEP_MASK		(0x04)
#define V2_INITMSG_LOCKSTEP_LSBMASK		(0x01)
#define V2_INITMSG_LOCKSTEP_OFFSET		(0x0010)
#define V2_INITMSG_LOCKSTEP_SHIFT		(2)
#define V2_INITMSG_LOCKSTEP_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_LOCKSTEP_TRUSTED		(IMG_FALSE)

// V2_INITMSG     PEFORMANCELOG
#define V2_INITMSG_PEFORMANCELOG_START_BIT		3
#define V2_INITMSG_PEFORMANCELOG_END_BIT		3
#define V2_INITMSG_PEFORMANCELOG_ALIGNMENT		(1)
#define V2_INITMSG_PEFORMANCELOG_TYPE		IMG_UINT8
#define V2_INITMSG_PEFORMANCELOG_MASK		(0x08)
#define V2_INITMSG_PEFORMANCELOG_LSBMASK		(0x01)
#define V2_INITMSG_PEFORMANCELOG_OFFSET		(0x0010)
#define V2_INITMSG_PEFORMANCELOG_SHIFT		(3)
#define V2_INITMSG_PEFORMANCELOG_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_PEFORMANCELOG_TRUSTED		(IMG_FALSE)

// V2_INITMSG     DISABLEOPT
#define V2_INITMSG_DISABLEOPT_START_BIT		4
#define V2_INITMSG_DISABLEOPT_END_BIT		4
#define V2_INITMSG_DISABLEOPT_ALIGNMENT		(1)
#define V2_INITMSG_DISABLEOPT_TYPE		IMG_UINT8
#define V2_INITMSG_DISABLEOPT_MASK		(0x10)
#define V2_INITMSG_DISABLEOPT_LSBMASK		(0x01)
#define V2_INITMSG_DISABLEOPT_OFFSET		(0x0010)
#define V2_INITMSG_DISABLEOPT_SHIFT		(4)
#define V2_INITMSG_DISABLEOPT_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_DISABLEOPT_TRUSTED		(IMG_FALSE)

// V2_INITMSG     MMU_CONTROL2
#define V2_INITMSG_MMU_CONTROL2_START_BIT		0
#define V2_INITMSG_MMU_CONTROL2_END_BIT		31
#define V2_INITMSG_MMU_CONTROL2_ALIGNMENT		(4)
#define V2_INITMSG_MMU_CONTROL2_TYPE		IMG_UINT32
#define V2_INITMSG_MMU_CONTROL2_MASK		(0xFFFFFFFF)
#define V2_INITMSG_MMU_CONTROL2_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_MMU_CONTROL2_OFFSET		(0x0028)
#define V2_INITMSG_MMU_CONTROL2_SHIFT		(0)
#define V2_INITMSG_MMU_CONTROL2_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_MMU_CONTROL2_TRUSTED		(IMG_FALSE)

// V2_INITMSG     MMU_36_BIT_TWIDDLE
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_START_BIT		0
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_END_BIT		0
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_ALIGNMENT		(1)
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_TYPE		IMG_UINT8
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_MASK		(0x01)
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_LSBMASK		(0x01)
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_OFFSET		(0x0050)
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_SHIFT		(0)
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_MMU_36_BIT_TWIDDLE_TRUSTED		(IMG_FALSE)

// V2_INITMSG     RENDEC_CONTROL0
#define V2_INITMSG_RENDEC_CONTROL0_START_BIT		0
#define V2_INITMSG_RENDEC_CONTROL0_END_BIT		31
#define V2_INITMSG_RENDEC_CONTROL0_ALIGNMENT		(4)
#define V2_INITMSG_RENDEC_CONTROL0_TYPE		IMG_UINT32
#define V2_INITMSG_RENDEC_CONTROL0_MASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_CONTROL0_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_CONTROL0_OFFSET		(0x0058)
#define V2_INITMSG_RENDEC_CONTROL0_SHIFT		(0)
#define V2_INITMSG_RENDEC_CONTROL0_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_RENDEC_CONTROL0_TRUSTED		(IMG_FALSE)

// V2_INITMSG     RENDEC_CONTROL1
#define V2_INITMSG_RENDEC_CONTROL1_START_BIT		0
#define V2_INITMSG_RENDEC_CONTROL1_END_BIT		31
#define V2_INITMSG_RENDEC_CONTROL1_ALIGNMENT		(4)
#define V2_INITMSG_RENDEC_CONTROL1_TYPE		IMG_UINT32
#define V2_INITMSG_RENDEC_CONTROL1_MASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_CONTROL1_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_CONTROL1_OFFSET		(0x0060)
#define V2_INITMSG_RENDEC_CONTROL1_SHIFT		(0)
#define V2_INITMSG_RENDEC_CONTROL1_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_RENDEC_CONTROL1_TRUSTED		(IMG_FALSE)

// V2_INITMSG     RENDEC_BUFFER_ADDR0
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_START_BIT		0
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_END_BIT		31
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_ALIGNMENT		(4)
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_TYPE		IMG_UINT32
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_MASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_OFFSET		(0x0068)
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_SHIFT		(0)
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_RENDEC_BUFFER_ADDR0_TRUSTED		(IMG_FALSE)

// V2_INITMSG     RENDEC_BUFFER_ADDR1
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_START_BIT		0
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_END_BIT		31
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_ALIGNMENT		(4)
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_TYPE		IMG_UINT32
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_MASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_OFFSET		(0x0070)
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_SHIFT		(0)
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_RENDEC_BUFFER_ADDR1_TRUSTED		(IMG_FALSE)

// V2_INITMSG     RENDEC_BUFFER_SIZE
#define V2_INITMSG_RENDEC_BUFFER_SIZE_START_BIT		0
#define V2_INITMSG_RENDEC_BUFFER_SIZE_END_BIT		31
#define V2_INITMSG_RENDEC_BUFFER_SIZE_ALIGNMENT		(4)
#define V2_INITMSG_RENDEC_BUFFER_SIZE_TYPE		IMG_UINT32
#define V2_INITMSG_RENDEC_BUFFER_SIZE_MASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_BUFFER_SIZE_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_RENDEC_BUFFER_SIZE_OFFSET		(0x0078)
#define V2_INITMSG_RENDEC_BUFFER_SIZE_SHIFT		(0)
#define V2_INITMSG_RENDEC_BUFFER_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_RENDEC_BUFFER_SIZE_TRUSTED		(IMG_FALSE)

// V2_INITMSG     VEC_CONTROL_2
#define V2_INITMSG_VEC_CONTROL_2_START_BIT		0
#define V2_INITMSG_VEC_CONTROL_2_END_BIT		31
#define V2_INITMSG_VEC_CONTROL_2_ALIGNMENT		(4)
#define V2_INITMSG_VEC_CONTROL_2_TYPE		IMG_UINT32
#define V2_INITMSG_VEC_CONTROL_2_MASK		(0xFFFFFFFF)
#define V2_INITMSG_VEC_CONTROL_2_LSBMASK		(0xFFFFFFFF)
#define V2_INITMSG_VEC_CONTROL_2_OFFSET		(0x0098)
#define V2_INITMSG_VEC_CONTROL_2_SHIFT		(0)
#define V2_INITMSG_VEC_CONTROL_2_SIGNED_FIELD	IMG_FALSE
#define V2_INITMSG_VEC_CONTROL_2_TRUSTED		(IMG_FALSE)

#define V2_CONFIGMSG_SIZE		(20)

// V2_CONFIGMSG     SIZE
#define V2_CONFIGMSG_SIZE_START_BIT		0
#define V2_CONFIGMSG_SIZE_END_BIT		7
#define V2_CONFIGMSG_SIZE_ALIGNMENT		(1)
#define V2_CONFIGMSG_SIZE_TYPE		IMG_UINT8
#define V2_CONFIGMSG_SIZE_MASK		(0xFF)
#define V2_CONFIGMSG_SIZE_LSBMASK		(0xFF)
#define V2_CONFIGMSG_SIZE_OFFSET		(0x0000)
#define V2_CONFIGMSG_SIZE_SHIFT		(0)
#define V2_CONFIGMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_CONFIGMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_CONFIGMSG     MID
#define V2_CONFIGMSG_MID_START_BIT		8
#define V2_CONFIGMSG_MID_END_BIT		15
#define V2_CONFIGMSG_MID_ALIGNMENT		(1)
#define V2_CONFIGMSG_MID_TYPE		IMG_UINT8
#define V2_CONFIGMSG_MID_MASK		(0xFF)
#define V2_CONFIGMSG_MID_LSBMASK		(0xFF)
#define V2_CONFIGMSG_MID_OFFSET		(0x0001)
#define V2_CONFIGMSG_MID_SHIFT		(0)
#define V2_CONFIGMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_CONFIGMSG_MID_TRUSTED		(IMG_FALSE)

// V2_CONFIGMSG     TYPE
#define V2_CONFIGMSG_TYPE_START_BIT		16
#define V2_CONFIGMSG_TYPE_END_BIT		23
#define V2_CONFIGMSG_TYPE_ALIGNMENT		(1)
#define V2_CONFIGMSG_TYPE_TYPE		IMG_UINT8
#define V2_CONFIGMSG_TYPE_MASK		(0xFF)
#define V2_CONFIGMSG_TYPE_LSBMASK		(0xFF)
#define V2_CONFIGMSG_TYPE_OFFSET		(0x0002)
#define V2_CONFIGMSG_TYPE_SHIFT		(0)
#define V2_CONFIGMSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define V2_CONFIGMSG_TYPE_TRUSTED		(IMG_FALSE)

// V2_CONFIGMSG     FENCE_ID
#define V2_CONFIGMSG_FENCE_ID_START_BIT		24
#define V2_CONFIGMSG_FENCE_ID_END_BIT		31
#define V2_CONFIGMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_CONFIGMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_CONFIGMSG_FENCE_ID_MASK		(0xFF)
#define V2_CONFIGMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_CONFIGMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_CONFIGMSG_FENCE_ID_SHIFT		(0)
#define V2_CONFIGMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_CONFIGMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_CONFIGMSG     VALUE0
#define V2_CONFIGMSG_VALUE0_START_BIT		0
#define V2_CONFIGMSG_VALUE0_END_BIT		31
#define V2_CONFIGMSG_VALUE0_ALIGNMENT		(4)
#define V2_CONFIGMSG_VALUE0_TYPE		IMG_UINT32
#define V2_CONFIGMSG_VALUE0_MASK		(0xFFFFFFFF)
#define V2_CONFIGMSG_VALUE0_LSBMASK		(0xFFFFFFFF)
#define V2_CONFIGMSG_VALUE0_OFFSET		(0x0004)
#define V2_CONFIGMSG_VALUE0_SHIFT		(0)
#define V2_CONFIGMSG_VALUE0_SIGNED_FIELD	IMG_FALSE
#define V2_CONFIGMSG_VALUE0_TRUSTED		(IMG_FALSE)

// V2_CONFIGMSG     VALUE1
#define V2_CONFIGMSG_VALUE1_START_BIT		0
#define V2_CONFIGMSG_VALUE1_END_BIT		31
#define V2_CONFIGMSG_VALUE1_ALIGNMENT		(4)
#define V2_CONFIGMSG_VALUE1_TYPE		IMG_UINT32
#define V2_CONFIGMSG_VALUE1_MASK		(0xFFFFFFFF)
#define V2_CONFIGMSG_VALUE1_LSBMASK		(0xFFFFFFFF)
#define V2_CONFIGMSG_VALUE1_OFFSET		(0x0008)
#define V2_CONFIGMSG_VALUE1_SHIFT		(0)
#define V2_CONFIGMSG_VALUE1_SIGNED_FIELD	IMG_FALSE
#define V2_CONFIGMSG_VALUE1_TRUSTED		(IMG_FALSE)

// V2_CONFIGMSG     VALUE2
#define V2_CONFIGMSG_VALUE2_START_BIT		0
#define V2_CONFIGMSG_VALUE2_END_BIT		31
#define V2_CONFIGMSG_VALUE2_ALIGNMENT		(4)
#define V2_CONFIGMSG_VALUE2_TYPE		IMG_UINT32
#define V2_CONFIGMSG_VALUE2_MASK		(0xFFFFFFFF)
#define V2_CONFIGMSG_VALUE2_LSBMASK		(0xFFFFFFFF)
#define V2_CONFIGMSG_VALUE2_OFFSET		(0x000C)
#define V2_CONFIGMSG_VALUE2_SHIFT		(0)
#define V2_CONFIGMSG_VALUE2_SIGNED_FIELD	IMG_FALSE
#define V2_CONFIGMSG_VALUE2_TRUSTED		(IMG_FALSE)

// V2_CONFIGMSG     VALUE3
#define V2_CONFIGMSG_VALUE3_START_BIT		0
#define V2_CONFIGMSG_VALUE3_END_BIT		31
#define V2_CONFIGMSG_VALUE3_ALIGNMENT		(4)
#define V2_CONFIGMSG_VALUE3_TYPE		IMG_UINT32
#define V2_CONFIGMSG_VALUE3_MASK		(0xFFFFFFFF)
#define V2_CONFIGMSG_VALUE3_LSBMASK		(0xFFFFFFFF)
#define V2_CONFIGMSG_VALUE3_OFFSET		(0x0010)
#define V2_CONFIGMSG_VALUE3_SHIFT		(0)
#define V2_CONFIGMSG_VALUE3_SIGNED_FIELD	IMG_FALSE
#define V2_CONFIGMSG_VALUE3_TRUSTED		(IMG_FALSE)

#define V2_CONTROLMSG_SIZE		(12)

// V2_CONTROLMSG     SIZE
#define V2_CONTROLMSG_SIZE_START_BIT		0
#define V2_CONTROLMSG_SIZE_END_BIT		7
#define V2_CONTROLMSG_SIZE_ALIGNMENT		(1)
#define V2_CONTROLMSG_SIZE_TYPE		IMG_UINT8
#define V2_CONTROLMSG_SIZE_MASK		(0xFF)
#define V2_CONTROLMSG_SIZE_LSBMASK		(0xFF)
#define V2_CONTROLMSG_SIZE_OFFSET		(0x0000)
#define V2_CONTROLMSG_SIZE_SHIFT		(0)
#define V2_CONTROLMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_CONTROLMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_CONTROLMSG     MID
#define V2_CONTROLMSG_MID_START_BIT		8
#define V2_CONTROLMSG_MID_END_BIT		15
#define V2_CONTROLMSG_MID_ALIGNMENT		(1)
#define V2_CONTROLMSG_MID_TYPE		IMG_UINT8
#define V2_CONTROLMSG_MID_MASK		(0xFF)
#define V2_CONTROLMSG_MID_LSBMASK		(0xFF)
#define V2_CONTROLMSG_MID_OFFSET		(0x0001)
#define V2_CONTROLMSG_MID_SHIFT		(0)
#define V2_CONTROLMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_CONTROLMSG_MID_TRUSTED		(IMG_FALSE)

// V2_CONTROLMSG     TYPE
#define V2_CONTROLMSG_TYPE_START_BIT		16
#define V2_CONTROLMSG_TYPE_END_BIT		23
#define V2_CONTROLMSG_TYPE_ALIGNMENT		(1)
#define V2_CONTROLMSG_TYPE_TYPE		IMG_UINT8
#define V2_CONTROLMSG_TYPE_MASK		(0xFF)
#define V2_CONTROLMSG_TYPE_LSBMASK		(0xFF)
#define V2_CONTROLMSG_TYPE_OFFSET		(0x0002)
#define V2_CONTROLMSG_TYPE_SHIFT		(0)
#define V2_CONTROLMSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define V2_CONTROLMSG_TYPE_TRUSTED		(IMG_FALSE)

// V2_CONTROLMSG     FENCE_ID
#define V2_CONTROLMSG_FENCE_ID_START_BIT		24
#define V2_CONTROLMSG_FENCE_ID_END_BIT		31
#define V2_CONTROLMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_CONTROLMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_CONTROLMSG_FENCE_ID_MASK		(0xFF)
#define V2_CONTROLMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_CONTROLMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_CONTROLMSG_FENCE_ID_SHIFT		(0)
#define V2_CONTROLMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_CONTROLMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_CONTROLMSG     VALUE0
#define V2_CONTROLMSG_VALUE0_START_BIT		0
#define V2_CONTROLMSG_VALUE0_END_BIT		31
#define V2_CONTROLMSG_VALUE0_ALIGNMENT		(4)
#define V2_CONTROLMSG_VALUE0_TYPE		IMG_UINT32
#define V2_CONTROLMSG_VALUE0_MASK		(0xFFFFFFFF)
#define V2_CONTROLMSG_VALUE0_LSBMASK		(0xFFFFFFFF)
#define V2_CONTROLMSG_VALUE0_OFFSET		(0x0004)
#define V2_CONTROLMSG_VALUE0_SHIFT		(0)
#define V2_CONTROLMSG_VALUE0_SIGNED_FIELD	IMG_FALSE
#define V2_CONTROLMSG_VALUE0_TRUSTED		(IMG_FALSE)

// V2_CONTROLMSG     VALUE1
#define V2_CONTROLMSG_VALUE1_START_BIT		0
#define V2_CONTROLMSG_VALUE1_END_BIT		31
#define V2_CONTROLMSG_VALUE1_ALIGNMENT		(4)
#define V2_CONTROLMSG_VALUE1_TYPE		IMG_UINT32
#define V2_CONTROLMSG_VALUE1_MASK		(0xFFFFFFFF)
#define V2_CONTROLMSG_VALUE1_LSBMASK		(0xFFFFFFFF)
#define V2_CONTROLMSG_VALUE1_OFFSET		(0x0008)
#define V2_CONTROLMSG_VALUE1_SHIFT		(0)
#define V2_CONTROLMSG_VALUE1_SIGNED_FIELD	IMG_FALSE
#define V2_CONTROLMSG_VALUE1_TRUSTED		(IMG_FALSE)

#define V2_DECODEMSG_SIZE		(44)

// V2_DECODEMSG     SIZE
#define V2_DECODEMSG_SIZE_START_BIT		0
#define V2_DECODEMSG_SIZE_END_BIT		7
#define V2_DECODEMSG_SIZE_ALIGNMENT		(1)
#define V2_DECODEMSG_SIZE_TYPE		IMG_UINT8
#define V2_DECODEMSG_SIZE_MASK		(0xFF)
#define V2_DECODEMSG_SIZE_LSBMASK		(0xFF)
#define V2_DECODEMSG_SIZE_OFFSET		(0x0000)
#define V2_DECODEMSG_SIZE_SHIFT		(0)
#define V2_DECODEMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     MID
#define V2_DECODEMSG_MID_START_BIT		8
#define V2_DECODEMSG_MID_END_BIT		15
#define V2_DECODEMSG_MID_ALIGNMENT		(1)
#define V2_DECODEMSG_MID_TYPE		IMG_UINT8
#define V2_DECODEMSG_MID_MASK		(0xFF)
#define V2_DECODEMSG_MID_LSBMASK		(0xFF)
#define V2_DECODEMSG_MID_OFFSET		(0x0001)
#define V2_DECODEMSG_MID_SHIFT		(0)
#define V2_DECODEMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_MID_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     TYPE
#define V2_DECODEMSG_TYPE_START_BIT		16
#define V2_DECODEMSG_TYPE_END_BIT		23
#define V2_DECODEMSG_TYPE_ALIGNMENT		(1)
#define V2_DECODEMSG_TYPE_TYPE		IMG_UINT8
#define V2_DECODEMSG_TYPE_MASK		(0xFF)
#define V2_DECODEMSG_TYPE_LSBMASK		(0xFF)
#define V2_DECODEMSG_TYPE_OFFSET		(0x0002)
#define V2_DECODEMSG_TYPE_SHIFT		(0)
#define V2_DECODEMSG_TYPE_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_TYPE_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     FENCE_ID
#define V2_DECODEMSG_FENCE_ID_START_BIT		24
#define V2_DECODEMSG_FENCE_ID_END_BIT		31
#define V2_DECODEMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_DECODEMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_DECODEMSG_FENCE_ID_MASK		(0xFF)
#define V2_DECODEMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_DECODEMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_DECODEMSG_FENCE_ID_SHIFT		(0)
#define V2_DECODEMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     CODE
#define V2_DECODEMSG_CODE_START_BIT		0
#define V2_DECODEMSG_CODE_END_BIT		7
#define V2_DECODEMSG_CODE_ALIGNMENT		(1)
#define V2_DECODEMSG_CODE_TYPE		IMG_UINT8
#define V2_DECODEMSG_CODE_MASK		(0xFF)
#define V2_DECODEMSG_CODE_LSBMASK		(0xFF)
#define V2_DECODEMSG_CODE_OFFSET		(0x0004)
#define V2_DECODEMSG_CODE_SHIFT		(0)
#define V2_DECODEMSG_CODE_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_CODE_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     STREAM
#define V2_DECODEMSG_STREAM_START_BIT		8
#define V2_DECODEMSG_STREAM_END_BIT		15
#define V2_DECODEMSG_STREAM_ALIGNMENT		(1)
#define V2_DECODEMSG_STREAM_TYPE		IMG_UINT8
#define V2_DECODEMSG_STREAM_MASK		(0xFF)
#define V2_DECODEMSG_STREAM_LSBMASK		(0xFF)
#define V2_DECODEMSG_STREAM_OFFSET		(0x0005)
#define V2_DECODEMSG_STREAM_SHIFT		(0)
#define V2_DECODEMSG_STREAM_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_STREAM_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     TID
#define V2_DECODEMSG_TID_START_BIT		0
#define V2_DECODEMSG_TID_END_BIT		31
#define V2_DECODEMSG_TID_ALIGNMENT		(4)
#define V2_DECODEMSG_TID_TYPE		IMG_UINT32
#define V2_DECODEMSG_TID_MASK		(0xFFFFFFFF)
#define V2_DECODEMSG_TID_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEMSG_TID_OFFSET		(0x0008)
#define V2_DECODEMSG_TID_SHIFT		(0)
#define V2_DECODEMSG_TID_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_TID_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     DEPTID
#define V2_DECODEMSG_DEPTID_START_BIT		0
#define V2_DECODEMSG_DEPTID_END_BIT		23
#define V2_DECODEMSG_DEPTID_ALIGNMENT		(4)
#define V2_DECODEMSG_DEPTID_TYPE		IMG_UINT32
#define V2_DECODEMSG_DEPTID_MASK		(0x00FFFFFF)
#define V2_DECODEMSG_DEPTID_LSBMASK		(0x00FFFFFF)
#define V2_DECODEMSG_DEPTID_OFFSET		(0x000C)
#define V2_DECODEMSG_DEPTID_SHIFT		(0)
#define V2_DECODEMSG_DEPTID_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_DEPTID_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     DEPCORE
#define V2_DECODEMSG_DEPCORE_START_BIT		24
#define V2_DECODEMSG_DEPCORE_END_BIT		31
#define V2_DECODEMSG_DEPCORE_ALIGNMENT		(1)
#define V2_DECODEMSG_DEPCORE_TYPE		IMG_UINT8
#define V2_DECODEMSG_DEPCORE_MASK		(0xFF)
#define V2_DECODEMSG_DEPCORE_LSBMASK		(0xFF)
#define V2_DECODEMSG_DEPCORE_OFFSET		(0x000F)
#define V2_DECODEMSG_DEPCORE_SHIFT		(0)
#define V2_DECODEMSG_DEPCORE_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_DEPCORE_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     TRANSACTION_ADDR
#define V2_DECODEMSG_TRANSACTION_ADDR_START_BIT		0
#define V2_DECODEMSG_TRANSACTION_ADDR_END_BIT		31
#define V2_DECODEMSG_TRANSACTION_ADDR_ALIGNMENT		(4)
#define V2_DECODEMSG_TRANSACTION_ADDR_TYPE		IMG_UINT32
#define V2_DECODEMSG_TRANSACTION_ADDR_MASK		(0xFFFFFFFF)
#define V2_DECODEMSG_TRANSACTION_ADDR_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEMSG_TRANSACTION_ADDR_OFFSET		(0x0010)
#define V2_DECODEMSG_TRANSACTION_ADDR_SHIFT		(0)
#define V2_DECODEMSG_TRANSACTION_ADDR_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_TRANSACTION_ADDR_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     TRANSACTION_SIZE
#define V2_DECODEMSG_TRANSACTION_SIZE_START_BIT		0
#define V2_DECODEMSG_TRANSACTION_SIZE_END_BIT		31
#define V2_DECODEMSG_TRANSACTION_SIZE_ALIGNMENT		(4)
#define V2_DECODEMSG_TRANSACTION_SIZE_TYPE		IMG_UINT32
#define V2_DECODEMSG_TRANSACTION_SIZE_MASK		(0xFFFFFFFF)
#define V2_DECODEMSG_TRANSACTION_SIZE_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEMSG_TRANSACTION_SIZE_OFFSET		(0x0014)
#define V2_DECODEMSG_TRANSACTION_SIZE_SHIFT		(0)
#define V2_DECODEMSG_TRANSACTION_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_TRANSACTION_SIZE_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     STREAM_PTD
#define V2_DECODEMSG_STREAM_PTD_START_BIT		0
#define V2_DECODEMSG_STREAM_PTD_END_BIT		31
#define V2_DECODEMSG_STREAM_PTD_ALIGNMENT		(4)
#define V2_DECODEMSG_STREAM_PTD_TYPE		IMG_UINT32
#define V2_DECODEMSG_STREAM_PTD_MASK		(0xFFFFFFFF)
#define V2_DECODEMSG_STREAM_PTD_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEMSG_STREAM_PTD_OFFSET		(0x0018)
#define V2_DECODEMSG_STREAM_PTD_SHIFT		(0)
#define V2_DECODEMSG_STREAM_PTD_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_STREAM_PTD_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     PSRMODINFO_ADDR
#define V2_DECODEMSG_PSRMODINFO_ADDR_START_BIT		0
#define V2_DECODEMSG_PSRMODINFO_ADDR_END_BIT		63
#define V2_DECODEMSG_PSRMODINFO_ADDR_ALIGNMENT		(8)
#define V2_DECODEMSG_PSRMODINFO_ADDR_TYPE		IMG_UINT64
#define V2_DECODEMSG_PSRMODINFO_ADDR_MASK		(0xFFFFFFFFFFFFFFFFULL)
#define V2_DECODEMSG_PSRMODINFO_ADDR_LSBMASK		(0xFFFFFFFFFFFFFFFFULL)
#define V2_DECODEMSG_PSRMODINFO_ADDR_OFFSET		(0x0020)
#define V2_DECODEMSG_PSRMODINFO_ADDR_SHIFT		(0)
#define V2_DECODEMSG_PSRMODINFO_ADDR_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_PSRMODINFO_ADDR_TRUSTED		(IMG_FALSE)

// V2_DECODEMSG     PSRMODINFO_SIZE
#define V2_DECODEMSG_PSRMODINFO_SIZE_START_BIT		0
#define V2_DECODEMSG_PSRMODINFO_SIZE_END_BIT		31
#define V2_DECODEMSG_PSRMODINFO_SIZE_ALIGNMENT		(4)
#define V2_DECODEMSG_PSRMODINFO_SIZE_TYPE		IMG_UINT32
#define V2_DECODEMSG_PSRMODINFO_SIZE_MASK		(0xFFFFFFFF)
#define V2_DECODEMSG_PSRMODINFO_SIZE_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEMSG_PSRMODINFO_SIZE_OFFSET		(0x0028)
#define V2_DECODEMSG_PSRMODINFO_SIZE_SHIFT		(0)
#define V2_DECODEMSG_PSRMODINFO_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEMSG_PSRMODINFO_SIZE_TRUSTED		(IMG_FALSE)

#define V2_BUFFERMSG_SIZE		(12)

// V2_BUFFERMSG     SIZE
#define V2_BUFFERMSG_SIZE_START_BIT		0
#define V2_BUFFERMSG_SIZE_END_BIT		7
#define V2_BUFFERMSG_SIZE_ALIGNMENT		(1)
#define V2_BUFFERMSG_SIZE_TYPE		IMG_UINT8
#define V2_BUFFERMSG_SIZE_MASK		(0xFF)
#define V2_BUFFERMSG_SIZE_LSBMASK		(0xFF)
#define V2_BUFFERMSG_SIZE_OFFSET		(0x0000)
#define V2_BUFFERMSG_SIZE_SHIFT		(0)
#define V2_BUFFERMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_BUFFERMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_BUFFERMSG     MID
#define V2_BUFFERMSG_MID_START_BIT		8
#define V2_BUFFERMSG_MID_END_BIT		15
#define V2_BUFFERMSG_MID_ALIGNMENT		(1)
#define V2_BUFFERMSG_MID_TYPE		IMG_UINT8
#define V2_BUFFERMSG_MID_MASK		(0xFF)
#define V2_BUFFERMSG_MID_LSBMASK		(0xFF)
#define V2_BUFFERMSG_MID_OFFSET		(0x0001)
#define V2_BUFFERMSG_MID_SHIFT		(0)
#define V2_BUFFERMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_BUFFERMSG_MID_TRUSTED		(IMG_FALSE)

// V2_BUFFERMSG     FLAGS
#define V2_BUFFERMSG_FLAGS_START_BIT		16
#define V2_BUFFERMSG_FLAGS_END_BIT		23
#define V2_BUFFERMSG_FLAGS_ALIGNMENT		(1)
#define V2_BUFFERMSG_FLAGS_TYPE		IMG_UINT8
#define V2_BUFFERMSG_FLAGS_MASK		(0xFF)
#define V2_BUFFERMSG_FLAGS_LSBMASK		(0xFF)
#define V2_BUFFERMSG_FLAGS_OFFSET		(0x0002)
#define V2_BUFFERMSG_FLAGS_SHIFT		(0)
#define V2_BUFFERMSG_FLAGS_SIGNED_FIELD	IMG_FALSE
#define V2_BUFFERMSG_FLAGS_TRUSTED		(IMG_FALSE)

// V2_BUFFERMSG     FENCE_ID
#define V2_BUFFERMSG_FENCE_ID_START_BIT		24
#define V2_BUFFERMSG_FENCE_ID_END_BIT		31
#define V2_BUFFERMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_BUFFERMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_BUFFERMSG_FENCE_ID_MASK		(0xFF)
#define V2_BUFFERMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_BUFFERMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_BUFFERMSG_FENCE_ID_SHIFT		(0)
#define V2_BUFFERMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_BUFFERMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_BUFFERMSG     DATAADDR
#define V2_BUFFERMSG_DATAADDR_START_BIT		0
#define V2_BUFFERMSG_DATAADDR_END_BIT		31
#define V2_BUFFERMSG_DATAADDR_ALIGNMENT		(4)
#define V2_BUFFERMSG_DATAADDR_TYPE		IMG_UINT32
#define V2_BUFFERMSG_DATAADDR_MASK		(0xFFFFFFFF)
#define V2_BUFFERMSG_DATAADDR_LSBMASK		(0xFFFFFFFF)
#define V2_BUFFERMSG_DATAADDR_OFFSET		(0x0004)
#define V2_BUFFERMSG_DATAADDR_SHIFT		(0)
#define V2_BUFFERMSG_DATAADDR_SIGNED_FIELD	IMG_FALSE
#define V2_BUFFERMSG_DATAADDR_TRUSTED		(IMG_FALSE)

// V2_BUFFERMSG     DATASIZE
#define V2_BUFFERMSG_DATASIZE_START_BIT		32
#define V2_BUFFERMSG_DATASIZE_END_BIT		63
#define V2_BUFFERMSG_DATASIZE_ALIGNMENT		(4)
#define V2_BUFFERMSG_DATASIZE_TYPE		IMG_UINT32
#define V2_BUFFERMSG_DATASIZE_MASK		(0xFFFFFFFF)
#define V2_BUFFERMSG_DATASIZE_LSBMASK		(0xFFFFFFFF)
#define V2_BUFFERMSG_DATASIZE_OFFSET		(0x0008)
#define V2_BUFFERMSG_DATASIZE_SHIFT		(0)
#define V2_BUFFERMSG_DATASIZE_SIGNED_FIELD	IMG_FALSE
#define V2_BUFFERMSG_DATASIZE_TRUSTED		(IMG_FALSE)

#define V2_FENCEMSG_SIZE		(8)

// V2_FENCEMSG     SIZE
#define V2_FENCEMSG_SIZE_START_BIT		0
#define V2_FENCEMSG_SIZE_END_BIT		7
#define V2_FENCEMSG_SIZE_ALIGNMENT		(1)
#define V2_FENCEMSG_SIZE_TYPE		IMG_UINT8
#define V2_FENCEMSG_SIZE_MASK		(0xFF)
#define V2_FENCEMSG_SIZE_LSBMASK		(0xFF)
#define V2_FENCEMSG_SIZE_OFFSET		(0x0000)
#define V2_FENCEMSG_SIZE_SHIFT		(0)
#define V2_FENCEMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_FENCEMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_FENCEMSG     MID
#define V2_FENCEMSG_MID_START_BIT		8
#define V2_FENCEMSG_MID_END_BIT		15
#define V2_FENCEMSG_MID_ALIGNMENT		(1)
#define V2_FENCEMSG_MID_TYPE		IMG_UINT8
#define V2_FENCEMSG_MID_MASK		(0xFF)
#define V2_FENCEMSG_MID_LSBMASK		(0xFF)
#define V2_FENCEMSG_MID_OFFSET		(0x0001)
#define V2_FENCEMSG_MID_SHIFT		(0)
#define V2_FENCEMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_FENCEMSG_MID_TRUSTED		(IMG_FALSE)

// V2_FENCEMSG     FLAGS
#define V2_FENCEMSG_FLAGS_START_BIT		16
#define V2_FENCEMSG_FLAGS_END_BIT		23
#define V2_FENCEMSG_FLAGS_ALIGNMENT		(1)
#define V2_FENCEMSG_FLAGS_TYPE		IMG_UINT8
#define V2_FENCEMSG_FLAGS_MASK		(0xFF)
#define V2_FENCEMSG_FLAGS_LSBMASK		(0xFF)
#define V2_FENCEMSG_FLAGS_OFFSET		(0x0002)
#define V2_FENCEMSG_FLAGS_SHIFT		(0)
#define V2_FENCEMSG_FLAGS_SIGNED_FIELD	IMG_FALSE
#define V2_FENCEMSG_FLAGS_TRUSTED		(IMG_FALSE)

// V2_FENCEMSG     FENCE_ID
#define V2_FENCEMSG_FENCE_ID_START_BIT		24
#define V2_FENCEMSG_FENCE_ID_END_BIT		31
#define V2_FENCEMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_FENCEMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_FENCEMSG_FENCE_ID_MASK		(0xFF)
#define V2_FENCEMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_FENCEMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_FENCEMSG_FENCE_ID_SHIFT		(0)
#define V2_FENCEMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_FENCEMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_FENCEMSG     FENCE
#define V2_FENCEMSG_FENCE_START_BIT		0
#define V2_FENCEMSG_FENCE_END_BIT		31
#define V2_FENCEMSG_FENCE_ALIGNMENT		(4)
#define V2_FENCEMSG_FENCE_TYPE		IMG_UINT32
#define V2_FENCEMSG_FENCE_MASK		(0xFFFFFFFF)
#define V2_FENCEMSG_FENCE_LSBMASK		(0xFFFFFFFF)
#define V2_FENCEMSG_FENCE_OFFSET		(0x0004)
#define V2_FENCEMSG_FENCE_SHIFT		(0)
#define V2_FENCEMSG_FENCE_SIGNED_FIELD	IMG_FALSE
#define V2_FENCEMSG_FENCE_TRUSTED		(IMG_FALSE)

#define V2_BATCHMSG_SIZE		(16)

// V2_BATCHMSG     SIZE
#define V2_BATCHMSG_SIZE_START_BIT		0
#define V2_BATCHMSG_SIZE_END_BIT		7
#define V2_BATCHMSG_SIZE_ALIGNMENT		(1)
#define V2_BATCHMSG_SIZE_TYPE		IMG_UINT8
#define V2_BATCHMSG_SIZE_MASK		(0xFF)
#define V2_BATCHMSG_SIZE_LSBMASK		(0xFF)
#define V2_BATCHMSG_SIZE_OFFSET		(0x0000)
#define V2_BATCHMSG_SIZE_SHIFT		(0)
#define V2_BATCHMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_BATCHMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_BATCHMSG     MID
#define V2_BATCHMSG_MID_START_BIT		8
#define V2_BATCHMSG_MID_END_BIT		15
#define V2_BATCHMSG_MID_ALIGNMENT		(1)
#define V2_BATCHMSG_MID_TYPE		IMG_UINT8
#define V2_BATCHMSG_MID_MASK		(0xFF)
#define V2_BATCHMSG_MID_LSBMASK		(0xFF)
#define V2_BATCHMSG_MID_OFFSET		(0x0001)
#define V2_BATCHMSG_MID_SHIFT		(0)
#define V2_BATCHMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_BATCHMSG_MID_TRUSTED		(IMG_FALSE)

// V2_BATCHMSG     FLAGS
#define V2_BATCHMSG_FLAGS_START_BIT		16
#define V2_BATCHMSG_FLAGS_END_BIT		23
#define V2_BATCHMSG_FLAGS_ALIGNMENT		(1)
#define V2_BATCHMSG_FLAGS_TYPE		IMG_UINT8
#define V2_BATCHMSG_FLAGS_MASK		(0xFF)
#define V2_BATCHMSG_FLAGS_LSBMASK		(0xFF)
#define V2_BATCHMSG_FLAGS_OFFSET		(0x0002)
#define V2_BATCHMSG_FLAGS_SHIFT		(0)
#define V2_BATCHMSG_FLAGS_SIGNED_FIELD	IMG_FALSE
#define V2_BATCHMSG_FLAGS_TRUSTED		(IMG_FALSE)

// V2_BATCHMSG     FENCE_ID
#define V2_BATCHMSG_FENCE_ID_START_BIT		24
#define V2_BATCHMSG_FENCE_ID_END_BIT		31
#define V2_BATCHMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_BATCHMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_BATCHMSG_FENCE_ID_MASK		(0xFF)
#define V2_BATCHMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_BATCHMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_BATCHMSG_FENCE_ID_SHIFT		(0)
#define V2_BATCHMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_BATCHMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_BATCHMSG     STREAM_PTD
#define V2_BATCHMSG_STREAM_PTD_START_BIT		0
#define V2_BATCHMSG_STREAM_PTD_END_BIT		31
#define V2_BATCHMSG_STREAM_PTD_ALIGNMENT		(4)
#define V2_BATCHMSG_STREAM_PTD_TYPE		IMG_UINT32
#define V2_BATCHMSG_STREAM_PTD_MASK		(0xFFFFFFFF)
#define V2_BATCHMSG_STREAM_PTD_LSBMASK		(0xFFFFFFFF)
#define V2_BATCHMSG_STREAM_PTD_OFFSET		(0x0004)
#define V2_BATCHMSG_STREAM_PTD_SHIFT		(0)
#define V2_BATCHMSG_STREAM_PTD_SIGNED_FIELD	IMG_FALSE
#define V2_BATCHMSG_STREAM_PTD_TRUSTED		(IMG_FALSE)

// V2_BATCHMSG     BATCHADDR
#define V2_BATCHMSG_BATCHADDR_START_BIT		0
#define V2_BATCHMSG_BATCHADDR_END_BIT		31
#define V2_BATCHMSG_BATCHADDR_ALIGNMENT		(4)
#define V2_BATCHMSG_BATCHADDR_TYPE		IMG_UINT32
#define V2_BATCHMSG_BATCHADDR_MASK		(0xFFFFFFFF)
#define V2_BATCHMSG_BATCHADDR_LSBMASK		(0xFFFFFFFF)
#define V2_BATCHMSG_BATCHADDR_OFFSET		(0x0008)
#define V2_BATCHMSG_BATCHADDR_SHIFT		(0)
#define V2_BATCHMSG_BATCHADDR_SIGNED_FIELD	IMG_FALSE
#define V2_BATCHMSG_BATCHADDR_TRUSTED		(IMG_FALSE)

// V2_BATCHMSG     BATCHSIZE
#define V2_BATCHMSG_BATCHSIZE_START_BIT		0
#define V2_BATCHMSG_BATCHSIZE_END_BIT		31
#define V2_BATCHMSG_BATCHSIZE_ALIGNMENT		(4)
#define V2_BATCHMSG_BATCHSIZE_TYPE		IMG_UINT32
#define V2_BATCHMSG_BATCHSIZE_MASK		(0xFFFFFFFF)
#define V2_BATCHMSG_BATCHSIZE_LSBMASK		(0xFFFFFFFF)
#define V2_BATCHMSG_BATCHSIZE_OFFSET		(0x000C)
#define V2_BATCHMSG_BATCHSIZE_SHIFT		(0)
#define V2_BATCHMSG_BATCHSIZE_SIGNED_FIELD	IMG_FALSE
#define V2_BATCHMSG_BATCHSIZE_TRUSTED		(IMG_FALSE)

#define V2_DECODEDMSG_SIZE		(32)

// V2_DECODEDMSG     SIZE
#define V2_DECODEDMSG_SIZE_START_BIT		0
#define V2_DECODEDMSG_SIZE_END_BIT		7
#define V2_DECODEDMSG_SIZE_ALIGNMENT		(1)
#define V2_DECODEDMSG_SIZE_TYPE		IMG_UINT8
#define V2_DECODEDMSG_SIZE_MASK		(0xFF)
#define V2_DECODEDMSG_SIZE_LSBMASK		(0xFF)
#define V2_DECODEDMSG_SIZE_OFFSET		(0x0000)
#define V2_DECODEDMSG_SIZE_SHIFT		(0)
#define V2_DECODEDMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     MID
#define V2_DECODEDMSG_MID_START_BIT		8
#define V2_DECODEDMSG_MID_END_BIT		15
#define V2_DECODEDMSG_MID_ALIGNMENT		(1)
#define V2_DECODEDMSG_MID_TYPE		IMG_UINT8
#define V2_DECODEDMSG_MID_MASK		(0xFF)
#define V2_DECODEDMSG_MID_LSBMASK		(0xFF)
#define V2_DECODEDMSG_MID_OFFSET		(0x0001)
#define V2_DECODEDMSG_MID_SHIFT		(0)
#define V2_DECODEDMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_MID_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     FLAGS
#define V2_DECODEDMSG_FLAGS_START_BIT		16
#define V2_DECODEDMSG_FLAGS_END_BIT		23
#define V2_DECODEDMSG_FLAGS_ALIGNMENT		(1)
#define V2_DECODEDMSG_FLAGS_TYPE		IMG_UINT8
#define V2_DECODEDMSG_FLAGS_MASK		(0xFF)
#define V2_DECODEDMSG_FLAGS_LSBMASK		(0xFF)
#define V2_DECODEDMSG_FLAGS_OFFSET		(0x0002)
#define V2_DECODEDMSG_FLAGS_SHIFT		(0)
#define V2_DECODEDMSG_FLAGS_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_FLAGS_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     FENCE_ID
#define V2_DECODEDMSG_FENCE_ID_START_BIT		24
#define V2_DECODEDMSG_FENCE_ID_END_BIT		31
#define V2_DECODEDMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_DECODEDMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_DECODEDMSG_FENCE_ID_MASK		(0xFF)
#define V2_DECODEDMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_DECODEDMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_DECODEDMSG_FENCE_ID_SHIFT		(0)
#define V2_DECODEDMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     TID
#define V2_DECODEDMSG_TID_START_BIT		0
#define V2_DECODEDMSG_TID_END_BIT		31
#define V2_DECODEDMSG_TID_ALIGNMENT		(4)
#define V2_DECODEDMSG_TID_TYPE		IMG_UINT32
#define V2_DECODEDMSG_TID_MASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_TID_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_TID_OFFSET		(0x0004)
#define V2_DECODEDMSG_TID_SHIFT		(0)
#define V2_DECODEDMSG_TID_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_TID_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     FE_ERR
#define V2_DECODEDMSG_FE_ERR_START_BIT		0
#define V2_DECODEDMSG_FE_ERR_END_BIT		31
#define V2_DECODEDMSG_FE_ERR_ALIGNMENT		(4)
#define V2_DECODEDMSG_FE_ERR_TYPE		IMG_UINT32
#define V2_DECODEDMSG_FE_ERR_MASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_FE_ERR_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_FE_ERR_OFFSET		(0x0008)
#define V2_DECODEDMSG_FE_ERR_SHIFT		(0)
#define V2_DECODEDMSG_FE_ERR_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_FE_ERR_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     VDMC_ERR
#define V2_DECODEDMSG_VDMC_ERR_START_BIT		0
#define V2_DECODEDMSG_VDMC_ERR_END_BIT		31
#define V2_DECODEDMSG_VDMC_ERR_ALIGNMENT		(4)
#define V2_DECODEDMSG_VDMC_ERR_TYPE		IMG_UINT32
#define V2_DECODEDMSG_VDMC_ERR_MASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_VDMC_ERR_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_VDMC_ERR_OFFSET		(0x000C)
#define V2_DECODEDMSG_VDMC_ERR_SHIFT		(0)
#define V2_DECODEDMSG_VDMC_ERR_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_VDMC_ERR_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     VDEB_ERR
#define V2_DECODEDMSG_VDEB_ERR_START_BIT		32
#define V2_DECODEDMSG_VDEB_ERR_END_BIT		63
#define V2_DECODEDMSG_VDEB_ERR_ALIGNMENT		(4)
#define V2_DECODEDMSG_VDEB_ERR_TYPE		IMG_UINT32
#define V2_DECODEDMSG_VDEB_ERR_MASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_VDEB_ERR_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_VDEB_ERR_OFFSET		(0x0010)
#define V2_DECODEDMSG_VDEB_ERR_SHIFT		(0)
#define V2_DECODEDMSG_VDEB_ERR_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_VDEB_ERR_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     RENDEC
#define V2_DECODEDMSG_RENDEC_START_BIT		0
#define V2_DECODEDMSG_RENDEC_END_BIT		15
#define V2_DECODEDMSG_RENDEC_ALIGNMENT		(2)
#define V2_DECODEDMSG_RENDEC_TYPE		IMG_UINT16
#define V2_DECODEDMSG_RENDEC_MASK		(0xFFFF)
#define V2_DECODEDMSG_RENDEC_LSBMASK		(0xFFFF)
#define V2_DECODEDMSG_RENDEC_OFFSET		(0x0014)
#define V2_DECODEDMSG_RENDEC_SHIFT		(0)
#define V2_DECODEDMSG_RENDEC_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_RENDEC_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     BEWDT
#define V2_DECODEDMSG_BEWDT_START_BIT		16
#define V2_DECODEDMSG_BEWDT_END_BIT		31
#define V2_DECODEDMSG_BEWDT_ALIGNMENT		(2)
#define V2_DECODEDMSG_BEWDT_TYPE		IMG_UINT16
#define V2_DECODEDMSG_BEWDT_MASK		(0xFFFF)
#define V2_DECODEDMSG_BEWDT_LSBMASK		(0xFFFF)
#define V2_DECODEDMSG_BEWDT_OFFSET		(0x0016)
#define V2_DECODEDMSG_BEWDT_SHIFT		(0)
#define V2_DECODEDMSG_BEWDT_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_BEWDT_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     SKIPPED
#define V2_DECODEDMSG_SKIPPED_START_BIT		0
#define V2_DECODEDMSG_SKIPPED_END_BIT		15
#define V2_DECODEDMSG_SKIPPED_ALIGNMENT		(2)
#define V2_DECODEDMSG_SKIPPED_TYPE		IMG_UINT16
#define V2_DECODEDMSG_SKIPPED_MASK		(0xFFFF)
#define V2_DECODEDMSG_SKIPPED_LSBMASK		(0xFFFF)
#define V2_DECODEDMSG_SKIPPED_OFFSET		(0x0018)
#define V2_DECODEDMSG_SKIPPED_SHIFT		(0)
#define V2_DECODEDMSG_SKIPPED_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_SKIPPED_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     GOOD
#define V2_DECODEDMSG_GOOD_START_BIT		16
#define V2_DECODEDMSG_GOOD_END_BIT		31
#define V2_DECODEDMSG_GOOD_ALIGNMENT		(2)
#define V2_DECODEDMSG_GOOD_TYPE		IMG_UINT16
#define V2_DECODEDMSG_GOOD_MASK		(0xFFFF)
#define V2_DECODEDMSG_GOOD_LSBMASK		(0xFFFF)
#define V2_DECODEDMSG_GOOD_OFFSET		(0x001A)
#define V2_DECODEDMSG_GOOD_SHIFT		(0)
#define V2_DECODEDMSG_GOOD_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_GOOD_TRUSTED		(IMG_FALSE)

// V2_DECODEDMSG     FILLPICID
#define V2_DECODEDMSG_FILLPICID_START_BIT		0
#define V2_DECODEDMSG_FILLPICID_END_BIT		31
#define V2_DECODEDMSG_FILLPICID_ALIGNMENT		(4)
#define V2_DECODEDMSG_FILLPICID_TYPE		IMG_UINT32
#define V2_DECODEDMSG_FILLPICID_MASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_FILLPICID_LSBMASK		(0xFFFFFFFF)
#define V2_DECODEDMSG_FILLPICID_OFFSET		(0x001C)
#define V2_DECODEDMSG_FILLPICID_SHIFT		(0)
#define V2_DECODEDMSG_FILLPICID_SIGNED_FIELD	IMG_FALSE
#define V2_DECODEDMSG_FILLPICID_TRUSTED		(IMG_FALSE)

#define V2_CRCMSG_SIZE		(48)

// V2_CRCMSG     SIZE
#define V2_CRCMSG_SIZE_START_BIT		0
#define V2_CRCMSG_SIZE_END_BIT		7
#define V2_CRCMSG_SIZE_ALIGNMENT		(1)
#define V2_CRCMSG_SIZE_TYPE		IMG_UINT8
#define V2_CRCMSG_SIZE_MASK		(0xFF)
#define V2_CRCMSG_SIZE_LSBMASK		(0xFF)
#define V2_CRCMSG_SIZE_OFFSET		(0x0000)
#define V2_CRCMSG_SIZE_SHIFT		(0)
#define V2_CRCMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     MID
#define V2_CRCMSG_MID_START_BIT		8
#define V2_CRCMSG_MID_END_BIT		15
#define V2_CRCMSG_MID_ALIGNMENT		(1)
#define V2_CRCMSG_MID_TYPE		IMG_UINT8
#define V2_CRCMSG_MID_MASK		(0xFF)
#define V2_CRCMSG_MID_LSBMASK		(0xFF)
#define V2_CRCMSG_MID_OFFSET		(0x0001)
#define V2_CRCMSG_MID_SHIFT		(0)
#define V2_CRCMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_MID_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     FLAGS
#define V2_CRCMSG_FLAGS_START_BIT		16
#define V2_CRCMSG_FLAGS_END_BIT		23
#define V2_CRCMSG_FLAGS_ALIGNMENT		(1)
#define V2_CRCMSG_FLAGS_TYPE		IMG_UINT8
#define V2_CRCMSG_FLAGS_MASK		(0xFF)
#define V2_CRCMSG_FLAGS_LSBMASK		(0xFF)
#define V2_CRCMSG_FLAGS_OFFSET		(0x0002)
#define V2_CRCMSG_FLAGS_SHIFT		(0)
#define V2_CRCMSG_FLAGS_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_FLAGS_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     FENCE_ID
#define V2_CRCMSG_FENCE_ID_START_BIT		24
#define V2_CRCMSG_FENCE_ID_END_BIT		31
#define V2_CRCMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_CRCMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_CRCMSG_FENCE_ID_MASK		(0xFF)
#define V2_CRCMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_CRCMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_CRCMSG_FENCE_ID_SHIFT		(0)
#define V2_CRCMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     TID
#define V2_CRCMSG_TID_START_BIT		0
#define V2_CRCMSG_TID_END_BIT		31
#define V2_CRCMSG_TID_ALIGNMENT		(4)
#define V2_CRCMSG_TID_TYPE		IMG_UINT32
#define V2_CRCMSG_TID_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_TID_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_TID_OFFSET		(0x0004)
#define V2_CRCMSG_TID_SHIFT		(0)
#define V2_CRCMSG_TID_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_TID_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VEC_CMD
#define V2_CRCMSG_CRC_VEC_CMD_START_BIT		0
#define V2_CRCMSG_CRC_VEC_CMD_END_BIT		31
#define V2_CRCMSG_CRC_VEC_CMD_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VEC_CMD_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VEC_CMD_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VEC_CMD_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VEC_CMD_OFFSET		(0x0008)
#define V2_CRCMSG_CRC_VEC_CMD_SHIFT		(0)
#define V2_CRCMSG_CRC_VEC_CMD_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VEC_CMD_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VEC_IXFORM
#define V2_CRCMSG_CRC_VEC_IXFORM_START_BIT		0
#define V2_CRCMSG_CRC_VEC_IXFORM_END_BIT		31
#define V2_CRCMSG_CRC_VEC_IXFORM_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VEC_IXFORM_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VEC_IXFORM_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VEC_IXFORM_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VEC_IXFORM_OFFSET		(0x000C)
#define V2_CRCMSG_CRC_VEC_IXFORM_SHIFT		(0)
#define V2_CRCMSG_CRC_VEC_IXFORM_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VEC_IXFORM_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VDMC_PIXRECON
#define V2_CRCMSG_CRC_VDMC_PIXRECON_START_BIT		0
#define V2_CRCMSG_CRC_VDMC_PIXRECON_END_BIT		31
#define V2_CRCMSG_CRC_VDMC_PIXRECON_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VDMC_PIXRECON_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VDMC_PIXRECON_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDMC_PIXRECON_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDMC_PIXRECON_OFFSET		(0x0010)
#define V2_CRCMSG_CRC_VDMC_PIXRECON_SHIFT		(0)
#define V2_CRCMSG_CRC_VDMC_PIXRECON_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VDMC_PIXRECON_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VDEB_SYSMEM_WDATA
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_START_BIT		0
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_END_BIT		31
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_OFFSET		(0x0014)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_SHIFT		(0)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VDEB_SYSMEM_WDATA_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VDEB_SYSMEM_ADDR
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_START_BIT		0
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_END_BIT		31
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_OFFSET		(0x0018)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_SHIFT		(0)
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VDEB_SYSMEM_ADDR_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VDEB_BURSTB_WDATA
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_START_BIT		0
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_END_BIT		31
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_OFFSET		(0x001C)
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_SHIFT		(0)
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VDEB_BURSTB_WDATA_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VDEB_BURSTB_ADDR
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_START_BIT		0
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_END_BIT		31
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_OFFSET		(0x0020)
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_SHIFT		(0)
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VDEB_BURSTB_ADDR_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VDEB_SCALE_WDATA
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_START_BIT		0
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_END_BIT		31
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_OFFSET		(0x0024)
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_SHIFT		(0)
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VDEB_SCALE_WDATA_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_VDEB_SCALE_ADDR
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_START_BIT		0
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_END_BIT		31
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_OFFSET		(0x0028)
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_SHIFT		(0)
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_VDEB_SCALE_ADDR_TRUSTED		(IMG_FALSE)

// V2_CRCMSG     CRC_SR_FE
#define V2_CRCMSG_CRC_SR_FE_START_BIT		0
#define V2_CRCMSG_CRC_SR_FE_END_BIT		31
#define V2_CRCMSG_CRC_SR_FE_ALIGNMENT		(4)
#define V2_CRCMSG_CRC_SR_FE_TYPE		IMG_UINT32
#define V2_CRCMSG_CRC_SR_FE_MASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_SR_FE_LSBMASK		(0xFFFFFFFF)
#define V2_CRCMSG_CRC_SR_FE_OFFSET		(0x002C)
#define V2_CRCMSG_CRC_SR_FE_SHIFT		(0)
#define V2_CRCMSG_CRC_SR_FE_SIGNED_FIELD	IMG_FALSE
#define V2_CRCMSG_CRC_SR_FE_TRUSTED		(IMG_FALSE)

#define V2_PERFMSG_SIZE		(92)

// V2_PERFMSG     SIZE
#define V2_PERFMSG_SIZE_START_BIT		0
#define V2_PERFMSG_SIZE_END_BIT		7
#define V2_PERFMSG_SIZE_ALIGNMENT		(1)
#define V2_PERFMSG_SIZE_TYPE		IMG_UINT8
#define V2_PERFMSG_SIZE_MASK		(0xFF)
#define V2_PERFMSG_SIZE_LSBMASK		(0xFF)
#define V2_PERFMSG_SIZE_OFFSET		(0x0000)
#define V2_PERFMSG_SIZE_SHIFT		(0)
#define V2_PERFMSG_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_SIZE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     MID
#define V2_PERFMSG_MID_START_BIT		8
#define V2_PERFMSG_MID_END_BIT		15
#define V2_PERFMSG_MID_ALIGNMENT		(1)
#define V2_PERFMSG_MID_TYPE		IMG_UINT8
#define V2_PERFMSG_MID_MASK		(0xFF)
#define V2_PERFMSG_MID_LSBMASK		(0xFF)
#define V2_PERFMSG_MID_OFFSET		(0x0001)
#define V2_PERFMSG_MID_SHIFT		(0)
#define V2_PERFMSG_MID_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_MID_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     FLAGS
#define V2_PERFMSG_FLAGS_START_BIT		16
#define V2_PERFMSG_FLAGS_END_BIT		23
#define V2_PERFMSG_FLAGS_ALIGNMENT		(1)
#define V2_PERFMSG_FLAGS_TYPE		IMG_UINT8
#define V2_PERFMSG_FLAGS_MASK		(0xFF)
#define V2_PERFMSG_FLAGS_LSBMASK		(0xFF)
#define V2_PERFMSG_FLAGS_OFFSET		(0x0002)
#define V2_PERFMSG_FLAGS_SHIFT		(0)
#define V2_PERFMSG_FLAGS_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_FLAGS_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     FENCE_ID
#define V2_PERFMSG_FENCE_ID_START_BIT		24
#define V2_PERFMSG_FENCE_ID_END_BIT		31
#define V2_PERFMSG_FENCE_ID_ALIGNMENT		(1)
#define V2_PERFMSG_FENCE_ID_TYPE		IMG_UINT8
#define V2_PERFMSG_FENCE_ID_MASK		(0xFF)
#define V2_PERFMSG_FENCE_ID_LSBMASK		(0xFF)
#define V2_PERFMSG_FENCE_ID_OFFSET		(0x0003)
#define V2_PERFMSG_FENCE_ID_SHIFT		(0)
#define V2_PERFMSG_FENCE_ID_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_FENCE_ID_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     TID
#define V2_PERFMSG_TID_START_BIT		0
#define V2_PERFMSG_TID_END_BIT		31
#define V2_PERFMSG_TID_ALIGNMENT		(4)
#define V2_PERFMSG_TID_TYPE		IMG_UINT32
#define V2_PERFMSG_TID_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_TID_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_TID_OFFSET		(0x0004)
#define V2_PERFMSG_TID_SHIFT		(0)
#define V2_PERFMSG_TID_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_TID_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     WIDTH_MBS
#define V2_PERFMSG_WIDTH_MBS_START_BIT		0
#define V2_PERFMSG_WIDTH_MBS_END_BIT		15
#define V2_PERFMSG_WIDTH_MBS_ALIGNMENT		(2)
#define V2_PERFMSG_WIDTH_MBS_TYPE		IMG_UINT16
#define V2_PERFMSG_WIDTH_MBS_MASK		(0xFFFF)
#define V2_PERFMSG_WIDTH_MBS_LSBMASK		(0xFFFF)
#define V2_PERFMSG_WIDTH_MBS_OFFSET		(0x0008)
#define V2_PERFMSG_WIDTH_MBS_SHIFT		(0)
#define V2_PERFMSG_WIDTH_MBS_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_WIDTH_MBS_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     HEIGHT_MBS
#define V2_PERFMSG_HEIGHT_MBS_START_BIT		16
#define V2_PERFMSG_HEIGHT_MBS_END_BIT		31
#define V2_PERFMSG_HEIGHT_MBS_ALIGNMENT		(2)
#define V2_PERFMSG_HEIGHT_MBS_TYPE		IMG_UINT16
#define V2_PERFMSG_HEIGHT_MBS_MASK		(0xFFFF)
#define V2_PERFMSG_HEIGHT_MBS_LSBMASK		(0xFFFF)
#define V2_PERFMSG_HEIGHT_MBS_OFFSET		(0x000A)
#define V2_PERFMSG_HEIGHT_MBS_SHIFT		(0)
#define V2_PERFMSG_HEIGHT_MBS_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_HEIGHT_MBS_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     NUM_SLICES
#define V2_PERFMSG_NUM_SLICES_START_BIT		0
#define V2_PERFMSG_NUM_SLICES_END_BIT		15
#define V2_PERFMSG_NUM_SLICES_ALIGNMENT		(2)
#define V2_PERFMSG_NUM_SLICES_TYPE		IMG_UINT16
#define V2_PERFMSG_NUM_SLICES_MASK		(0xFFFF)
#define V2_PERFMSG_NUM_SLICES_LSBMASK		(0xFFFF)
#define V2_PERFMSG_NUM_SLICES_OFFSET		(0x000C)
#define V2_PERFMSG_NUM_SLICES_SHIFT		(0)
#define V2_PERFMSG_NUM_SLICES_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_NUM_SLICES_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     1SLICE_SIZE
#define V2_PERFMSG_1SLICE_SIZE_START_BIT		16
#define V2_PERFMSG_1SLICE_SIZE_END_BIT		31
#define V2_PERFMSG_1SLICE_SIZE_ALIGNMENT		(2)
#define V2_PERFMSG_1SLICE_SIZE_TYPE		IMG_UINT16
#define V2_PERFMSG_1SLICE_SIZE_MASK		(0xFFFF)
#define V2_PERFMSG_1SLICE_SIZE_LSBMASK		(0xFFFF)
#define V2_PERFMSG_1SLICE_SIZE_OFFSET		(0x000E)
#define V2_PERFMSG_1SLICE_SIZE_SHIFT		(0)
#define V2_PERFMSG_1SLICE_SIZE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_1SLICE_SIZE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     PICTURE_STARTED
#define V2_PERFMSG_PICTURE_STARTED_START_BIT		0
#define V2_PERFMSG_PICTURE_STARTED_END_BIT		31
#define V2_PERFMSG_PICTURE_STARTED_ALIGNMENT		(4)
#define V2_PERFMSG_PICTURE_STARTED_TYPE		IMG_UINT32
#define V2_PERFMSG_PICTURE_STARTED_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_PICTURE_STARTED_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_PICTURE_STARTED_OFFSET		(0x0010)
#define V2_PERFMSG_PICTURE_STARTED_SHIFT		(0)
#define V2_PERFMSG_PICTURE_STARTED_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_PICTURE_STARTED_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     FIRMWARE_READY
#define V2_PERFMSG_FIRMWARE_READY_START_BIT		0
#define V2_PERFMSG_FIRMWARE_READY_END_BIT		31
#define V2_PERFMSG_FIRMWARE_READY_ALIGNMENT		(4)
#define V2_PERFMSG_FIRMWARE_READY_TYPE		IMG_UINT32
#define V2_PERFMSG_FIRMWARE_READY_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_FIRMWARE_READY_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_FIRMWARE_READY_OFFSET		(0x0014)
#define V2_PERFMSG_FIRMWARE_READY_SHIFT		(0)
#define V2_PERFMSG_FIRMWARE_READY_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_FIRMWARE_READY_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     PICMAN_COMPLETE
#define V2_PERFMSG_PICMAN_COMPLETE_START_BIT		0
#define V2_PERFMSG_PICMAN_COMPLETE_END_BIT		31
#define V2_PERFMSG_PICMAN_COMPLETE_ALIGNMENT		(4)
#define V2_PERFMSG_PICMAN_COMPLETE_TYPE		IMG_UINT32
#define V2_PERFMSG_PICMAN_COMPLETE_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_PICMAN_COMPLETE_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_PICMAN_COMPLETE_OFFSET		(0x0018)
#define V2_PERFMSG_PICMAN_COMPLETE_SHIFT		(0)
#define V2_PERFMSG_PICMAN_COMPLETE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_PICMAN_COMPLETE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     FIRMWARE_SAVED
#define V2_PERFMSG_FIRMWARE_SAVED_START_BIT		0
#define V2_PERFMSG_FIRMWARE_SAVED_END_BIT		31
#define V2_PERFMSG_FIRMWARE_SAVED_ALIGNMENT		(4)
#define V2_PERFMSG_FIRMWARE_SAVED_TYPE		IMG_UINT32
#define V2_PERFMSG_FIRMWARE_SAVED_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_FIRMWARE_SAVED_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_FIRMWARE_SAVED_OFFSET		(0x001C)
#define V2_PERFMSG_FIRMWARE_SAVED_SHIFT		(0)
#define V2_PERFMSG_FIRMWARE_SAVED_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_FIRMWARE_SAVED_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     ENTDEC_STARTED
#define V2_PERFMSG_ENTDEC_STARTED_START_BIT		0
#define V2_PERFMSG_ENTDEC_STARTED_END_BIT		31
#define V2_PERFMSG_ENTDEC_STARTED_ALIGNMENT		(4)
#define V2_PERFMSG_ENTDEC_STARTED_TYPE		IMG_UINT32
#define V2_PERFMSG_ENTDEC_STARTED_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_ENTDEC_STARTED_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_ENTDEC_STARTED_OFFSET		(0x0020)
#define V2_PERFMSG_ENTDEC_STARTED_SHIFT		(0)
#define V2_PERFMSG_ENTDEC_STARTED_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_ENTDEC_STARTED_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     FE_1SLICE_DONE
#define V2_PERFMSG_FE_1SLICE_DONE_START_BIT		0
#define V2_PERFMSG_FE_1SLICE_DONE_END_BIT		31
#define V2_PERFMSG_FE_1SLICE_DONE_ALIGNMENT		(4)
#define V2_PERFMSG_FE_1SLICE_DONE_TYPE		IMG_UINT32
#define V2_PERFMSG_FE_1SLICE_DONE_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_FE_1SLICE_DONE_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_FE_1SLICE_DONE_OFFSET		(0x0024)
#define V2_PERFMSG_FE_1SLICE_DONE_SHIFT		(0)
#define V2_PERFMSG_FE_1SLICE_DONE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_FE_1SLICE_DONE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     FE_PICTURE_COMPLETE
#define V2_PERFMSG_FE_PICTURE_COMPLETE_START_BIT		0
#define V2_PERFMSG_FE_PICTURE_COMPLETE_END_BIT		31
#define V2_PERFMSG_FE_PICTURE_COMPLETE_ALIGNMENT		(4)
#define V2_PERFMSG_FE_PICTURE_COMPLETE_TYPE		IMG_UINT32
#define V2_PERFMSG_FE_PICTURE_COMPLETE_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_FE_PICTURE_COMPLETE_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_FE_PICTURE_COMPLETE_OFFSET		(0x0028)
#define V2_PERFMSG_FE_PICTURE_COMPLETE_SHIFT		(0)
#define V2_PERFMSG_FE_PICTURE_COMPLETE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_FE_PICTURE_COMPLETE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     BE_PICTURE_STARTED
#define V2_PERFMSG_BE_PICTURE_STARTED_START_BIT		0
#define V2_PERFMSG_BE_PICTURE_STARTED_END_BIT		31
#define V2_PERFMSG_BE_PICTURE_STARTED_ALIGNMENT		(4)
#define V2_PERFMSG_BE_PICTURE_STARTED_TYPE		IMG_UINT32
#define V2_PERFMSG_BE_PICTURE_STARTED_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_BE_PICTURE_STARTED_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_BE_PICTURE_STARTED_OFFSET		(0x002C)
#define V2_PERFMSG_BE_PICTURE_STARTED_SHIFT		(0)
#define V2_PERFMSG_BE_PICTURE_STARTED_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_BE_PICTURE_STARTED_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     BE_1SLICE_DONE
#define V2_PERFMSG_BE_1SLICE_DONE_START_BIT		0
#define V2_PERFMSG_BE_1SLICE_DONE_END_BIT		31
#define V2_PERFMSG_BE_1SLICE_DONE_ALIGNMENT		(4)
#define V2_PERFMSG_BE_1SLICE_DONE_TYPE		IMG_UINT32
#define V2_PERFMSG_BE_1SLICE_DONE_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_BE_1SLICE_DONE_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_BE_1SLICE_DONE_OFFSET		(0x0030)
#define V2_PERFMSG_BE_1SLICE_DONE_SHIFT		(0)
#define V2_PERFMSG_BE_1SLICE_DONE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_BE_1SLICE_DONE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     BE_PICTURE_COMPLETE
#define V2_PERFMSG_BE_PICTURE_COMPLETE_START_BIT		0
#define V2_PERFMSG_BE_PICTURE_COMPLETE_END_BIT		31
#define V2_PERFMSG_BE_PICTURE_COMPLETE_ALIGNMENT		(4)
#define V2_PERFMSG_BE_PICTURE_COMPLETE_TYPE		IMG_UINT32
#define V2_PERFMSG_BE_PICTURE_COMPLETE_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_BE_PICTURE_COMPLETE_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_BE_PICTURE_COMPLETE_OFFSET		(0x0034)
#define V2_PERFMSG_BE_PICTURE_COMPLETE_SHIFT		(0)
#define V2_PERFMSG_BE_PICTURE_COMPLETE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_BE_PICTURE_COMPLETE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     TOT_HW_FE_DECODE
#define V2_PERFMSG_TOT_HW_FE_DECODE_START_BIT		0
#define V2_PERFMSG_TOT_HW_FE_DECODE_END_BIT		31
#define V2_PERFMSG_TOT_HW_FE_DECODE_ALIGNMENT		(4)
#define V2_PERFMSG_TOT_HW_FE_DECODE_TYPE		IMG_UINT32
#define V2_PERFMSG_TOT_HW_FE_DECODE_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_TOT_HW_FE_DECODE_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_TOT_HW_FE_DECODE_OFFSET		(0x0038)
#define V2_PERFMSG_TOT_HW_FE_DECODE_SHIFT		(0)
#define V2_PERFMSG_TOT_HW_FE_DECODE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_TOT_HW_FE_DECODE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     TOT_HW_BE_DECODE
#define V2_PERFMSG_TOT_HW_BE_DECODE_START_BIT		0
#define V2_PERFMSG_TOT_HW_BE_DECODE_END_BIT		31
#define V2_PERFMSG_TOT_HW_BE_DECODE_ALIGNMENT		(4)
#define V2_PERFMSG_TOT_HW_BE_DECODE_TYPE		IMG_UINT32
#define V2_PERFMSG_TOT_HW_BE_DECODE_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_TOT_HW_BE_DECODE_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_TOT_HW_BE_DECODE_OFFSET		(0x003C)
#define V2_PERFMSG_TOT_HW_BE_DECODE_SHIFT		(0)
#define V2_PERFMSG_TOT_HW_BE_DECODE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_TOT_HW_BE_DECODE_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     PARSE_AND_SETUP_REG
#define V2_PERFMSG_PARSE_AND_SETUP_REG_START_BIT		0
#define V2_PERFMSG_PARSE_AND_SETUP_REG_END_BIT		31
#define V2_PERFMSG_PARSE_AND_SETUP_REG_ALIGNMENT		(4)
#define V2_PERFMSG_PARSE_AND_SETUP_REG_TYPE		IMG_UINT32
#define V2_PERFMSG_PARSE_AND_SETUP_REG_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_PARSE_AND_SETUP_REG_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_PARSE_AND_SETUP_REG_OFFSET		(0x0040)
#define V2_PERFMSG_PARSE_AND_SETUP_REG_SHIFT		(0)
#define V2_PERFMSG_PARSE_AND_SETUP_REG_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_PARSE_AND_SETUP_REG_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     T1
#define V2_PERFMSG_T1_START_BIT		0
#define V2_PERFMSG_T1_END_BIT		31
#define V2_PERFMSG_T1_ALIGNMENT		(4)
#define V2_PERFMSG_T1_TYPE		IMG_UINT32
#define V2_PERFMSG_T1_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_T1_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_T1_OFFSET		(0x0044)
#define V2_PERFMSG_T1_SHIFT		(0)
#define V2_PERFMSG_T1_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_T1_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     T2
#define V2_PERFMSG_T2_START_BIT		0
#define V2_PERFMSG_T2_END_BIT		31
#define V2_PERFMSG_T2_ALIGNMENT		(4)
#define V2_PERFMSG_T2_TYPE		IMG_UINT32
#define V2_PERFMSG_T2_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_T2_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_T2_OFFSET		(0x0048)
#define V2_PERFMSG_T2_SHIFT		(0)
#define V2_PERFMSG_T2_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_T2_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     T3
#define V2_PERFMSG_T3_START_BIT		0
#define V2_PERFMSG_T3_END_BIT		31
#define V2_PERFMSG_T3_ALIGNMENT		(4)
#define V2_PERFMSG_T3_TYPE		IMG_UINT32
#define V2_PERFMSG_T3_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_T3_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_T3_OFFSET		(0x004C)
#define V2_PERFMSG_T3_SHIFT		(0)
#define V2_PERFMSG_T3_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_T3_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     T4
#define V2_PERFMSG_T4_START_BIT		0
#define V2_PERFMSG_T4_END_BIT		31
#define V2_PERFMSG_T4_ALIGNMENT		(4)
#define V2_PERFMSG_T4_TYPE		IMG_UINT32
#define V2_PERFMSG_T4_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_T4_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_T4_OFFSET		(0x0050)
#define V2_PERFMSG_T4_SHIFT		(0)
#define V2_PERFMSG_T4_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_T4_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     SYNC_START
#define V2_PERFMSG_SYNC_START_START_BIT		0
#define V2_PERFMSG_SYNC_START_END_BIT		31
#define V2_PERFMSG_SYNC_START_ALIGNMENT		(4)
#define V2_PERFMSG_SYNC_START_TYPE		IMG_UINT32
#define V2_PERFMSG_SYNC_START_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_SYNC_START_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_SYNC_START_OFFSET		(0x0054)
#define V2_PERFMSG_SYNC_START_SHIFT		(0)
#define V2_PERFMSG_SYNC_START_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_SYNC_START_TRUSTED		(IMG_FALSE)

// V2_PERFMSG     SYNC_COMPLETE
#define V2_PERFMSG_SYNC_COMPLETE_START_BIT		0
#define V2_PERFMSG_SYNC_COMPLETE_END_BIT		31
#define V2_PERFMSG_SYNC_COMPLETE_ALIGNMENT		(4)
#define V2_PERFMSG_SYNC_COMPLETE_TYPE		IMG_UINT32
#define V2_PERFMSG_SYNC_COMPLETE_MASK		(0xFFFFFFFF)
#define V2_PERFMSG_SYNC_COMPLETE_LSBMASK		(0xFFFFFFFF)
#define V2_PERFMSG_SYNC_COMPLETE_OFFSET		(0x0058)
#define V2_PERFMSG_SYNC_COMPLETE_SHIFT		(0)
#define V2_PERFMSG_SYNC_COMPLETE_SIGNED_FIELD	IMG_FALSE
#define V2_PERFMSG_SYNC_COMPLETE_TRUSTED		(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __VDECFW_MSG_MEM_IO_H__ */
