obj-$(CONFIG_OF) += hisi_hi3630_of_coresight.o
obj-$(CONFIG_HISI_CS) += hisi_hi3630_coresight.o hisi_hi3630_coresight_tmc.o hisi_hi3630_coresight_funnel.o hisi_hi3630_coresight_stm.o hisi_hi3630_coresight_etm.o
