OAMDIR = ..

MODEM_DIR := $(srctree)/$(src)/../..

ifeq ($(KERNEL_ARM_TYPE), arm64)
EXTRA_CFLAGS += -Iarch/arm64/include/asm
else
EXTRA_CFLAGS += -Iarch/arm/include/asm
endif
EXTRA_CFLAGS += -Iinclude/linux
EXTRA_CFLAGS += -Iinclude/generated
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/nvim/include/gu/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/osa/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/nvim/include/lt/tlps/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/product/$(OBB_PRODUCT_NAME)/config/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/product/$(OBB_PRODUCT_NAME)/include/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/drv/acore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/drv/common/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/med/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/osa/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/scm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/si/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/socp/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/usimm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/errno/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/dms/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/cpm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/log/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/hpa/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/lt/acore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/lt/common/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/phy/wphy/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/gups/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/tlps/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/nas/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/taf/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/tools/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/oam/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/drv/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/codec/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/gas/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/nas/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/phy/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/tool/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/ttf/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/was/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/acore/dms/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/ccore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/comm/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/acore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/usimm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/ccore/xml/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/comm/si/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/comm/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/comm/ppm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/cbtcpm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/cbtppm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/hpa/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/pstool/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/sc/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/sleep/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/comm/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/comm/bbplog/


#lt only INC
ifneq ($(CFG_RAT_MODE),RAT_GU)
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/acore/dms/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/comm/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/comm/si/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/ccore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/list/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/acore/diag/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/drx/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/cfg/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/diag/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/ipc/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/sdm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/type/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/taf/comm/src/acore/at/inc/
EXTRA_CFLAGS += -I$(MODEM_DIR)/taf/lt/inc/acore/at/
endif

EXTRA_CFLAGS +=  -DVOS_LINUX=4 -DOSA_CPU_ACPU=1 -DVOS_OS_VER=VOS_LINUX -DVOS_OSA_CPU=OSA_CPU_ACPU -D__LOG_RELEASE__ -DBSP_CORE_APP -DGU_MODE -DMSP_SUPPORT_USB_VCOM1 -DMSP_SUPPORT_USB_VCOM2 -DVOS_DOPRA_VER=2 -DNDIS_RELEASE -DBALONG_PHY_V200=2 -DBALONG_PHY_V300=3 -DBALONG_PHY_VER=BALONG_PHY_V300 -DBALONG_CHIP_V200=2 -DBALONG_CHIP_V300=3 -DBALONG_CHIP_V500=4 -DBALONG_CHIP_VER=BALONG_CHIP_V500 -DMSP_GUNAS_AT_UNITE

ifneq ($(KERNEL_ARM_TYPE), arm64)
EXTRA_CFLAGS += -D__LINUX_ARM_ARCH__=7 -march=armv7-a -Uarm
endif

ifneq ($(CFG_RAT_MODE),RAT_GU)
EXTRA_CFLAGS += -DPRODUCT_CFG_MULTIMODE_LTE -DHAL_DIAG_SDM_USE
endif


ifeq ($(strip $(OBB_UE_MODE_CDMA)),true)
EXTRA_CFLAGS += -DFEATURE_UE_MODE_CDMA=FEATURE_ON
else
EXTRA_CFLAGS += -DFEATURE_UE_MODE_CDMA=FEATURE_OFF
endif

EXTRA_CFLAGS += -fsigned-char 

gumsp-objs := $(OAMDIR)/comm/acore/om/omappcommrx.o
gumsp-objs += $(OAMDIR)/comm/acore/om/omapp.o
gumsp-objs += $(OAMDIR)/comm/acore/om/omapprl.o
gumsp-objs += $(OAMDIR)/comm/acore/om/omappoutside.o
gumsp-objs += $(OAMDIR)/comm/acore/om/omappagent.o
gumsp-objs += $(OAMDIR)/comm/acore/om/omprintf.o
gumsp-objs += $(OAMDIR)/gu/acore/om/ompcvoice.o
gumsp-objs += $(OAMDIR)/gu/acore/om/pamappom.o
gumsp-objs += $(OAMDIR)/gu/acore/usimm/usimmappbase.o
gumsp-objs += $(OAMDIR)/comm/acore/om/omsdlog.o
gumsp-objs += $(OAMDIR)/comm/acore/om/omerrorlog.o
gumsp-objs += $(OAMDIR)/gu/acore/bbplog/omappbbplog.o
gumsp-objs += $(OAMDIR)/comm/acore/om/Omappoperator.o
gumsp-objs += $(OAMDIR)/comm/acore/om/fastlz.o
gumsp-objs += $(OAMDIR)/gu/acore/cbtcpm/CbtCpm.o
gumsp-objs += $(OAMDIR)/gu/acore/cbtppm/CbtPpm.o
gumsp-objs += $(OAMDIR)/gu/acore/cbtscm/CBTSCMSoftDecode.o
gumsp-objs += $(OAMDIR)/gu/acore/cbtfun/cbtappfunction.o
gumsp-objs += $(OAMDIR)/gu/comm/om/OmHdlc.o
gumsp-objs += $(OAMDIR)/gu/comm/om/omringbuffer.o
gumsp-objs += $(OAMDIR)/gu/comm/om/ombufmngr.o
gumsp-objs += $(OAMDIR)/gu/acore/osa/linux_sem.o
gumsp-objs += $(OAMDIR)/gu/acore/osa/linux_task.o
gumsp-objs += $(OAMDIR)/gu/acore/si/PcscProc.o
gumsp-objs += $(OAMDIR)/comm/acore/cpm/cpm.o
gumsp-objs += $(OAMDIR)/comm/acore/ppm/OmCommonPpm.o
gumsp-objs += $(OAMDIR)/comm/acore/ppm/OmFsPpm.o
gumsp-objs += $(OAMDIR)/comm/acore/ppm/OmHsicPpm.o
gumsp-objs += $(OAMDIR)/comm/acore/ppm/OmSdPpm.o
gumsp-objs += $(OAMDIR)/comm/acore/ppm/OmSocketPpm.o
gumsp-objs += $(OAMDIR)/comm/acore/ppm/OmUsbPpm.o
gumsp-objs += $(OAMDIR)/comm/acore/ppm/OmVcomPpm.o
gumsp-objs += $(OAMDIR)/comm/acore/pslog/pslogapp.o
gumsp-objs += $(OAMDIR)/comm/acore/pslog/pslogadapterapp.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_blkmem.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_private.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_int.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/rtc_timer.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_queue.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_timer.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_msg.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_lib.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/vos_Id.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/vos_main.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/vos_outside.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/watchdog.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_nsprintf.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_sprintf.o
gumsp-objs += $(OAMDIR)/gu/comm/si/pbapi.o
gumsp-objs += $(OAMDIR)/gu/comm/si/pbmsg.o
gumsp-objs += $(OAMDIR)/gu/comm/si/pbdata.o
gumsp-objs += $(OAMDIR)/gu/comm/si/stkapi.o
gumsp-objs += $(OAMDIR)/gu/comm/si/pihapi.o
gumsp-objs += $(OAMDIR)/comm/comm/scm/SCMProc.o
gumsp-objs += $(OAMDIR)/comm/comm/scm/SCMSoftDecode.o
gumsp-objs += $(OAMDIR)/comm/comm/socp/BSP_SOCP.o

obj-y  := gumsp.o



