obj-$(CONFIG_BATTERY_COULOMB_TEST_INTERFACE_S)  += coulomb_test_interface.o
obj-$(CONFIG_BATTERY_HISI_HI6421V300_S)	+= hisi_battery_data.o hisi_hi6421v300_coul.o
obj-$(CONFIG_BATTERY_HISI_COUL_TEST_S)	+= hisi_coul_drv_test.o
obj-$(CONFIG_BATTERY_HISI_COUL_S)		+= hisi_coul_drv.o
obj-$(CONFIG_BQ_BCI_BATTERY_S)		+= bq_bci_battery.o
