
#ifndef _HISI_PARTITION_TABLE_H_
#define _HISI_PARTITION_TABLE_H_

/*分区名字*/
#define PART_FASTBOOT1         "fastboot1"
#define PART_PTALBE            "ptable"                 
#define PART_VRL               "vrl"               
#define PART_VRL_BKUP          "vrl_bkup"          
#define PART_MCUIMAGE          "mcuimage"          
#define PART_RESERVED0         "reserved0"         
#define PART_FASTBOOT          "fastboot"          
#define PART_MODEMNVBKUP       "modemnvbkup"       
#define PART_NVME              "nvme"              
#define PART_OEMINFO           "oeminfo"           
#define PART_SPLASH            "splash"            
#define PART_MODEMNVM1         "modemnvm1"         
#define PART_MODEMNVM2         "modemnvm2"         
#define PART_MODEMNVM3         "modemnvm3"         
#define PART_SECURETYSTORAGE   "securetystorage"   
#define PART_3RDMODEMNVM       "3rdmodemnvm"       
#define PART_3RDMODEMNVMBACK   "3rdmodemnvmback"   
#define PART_RESERVED1         "reserved1"         
#define PART_MODEMLOG          "modemlog"          
#define PART_SPLASH2           "splash2"           
#define PART_MISC              "misc"              
#define PART_MODEMNVRESERVED   "modemnvreserved"
#define PART_RECOVERY2         "recovery2"   
#define PART_RESERVED2         "reserved2" 
#define PART_TEEOS             "teeos"             
#define PART_TRUSTFIRMWARE     "trustfirmware"     
#define PART_SENSORHUB         "sensorhub"         
#define PART_HIFI              "hifi"              
#define PART_BOOT              "boot"              
#define PART_RECOVERY          "recovery"          
#define PART_DTIMAGE           "dtimage"           
#define PART_MODEMIMAGE        "modemimage"        
#define PART_DSP               "dsp"               
#define PART_DFX               "dfx"               
#define PART_3RDMODEM          "3rdmodem"          
#define PART_CACHE             "cache"             
#define PART_HISITEST0         "hisitest0"         
#define PART_HISITEST1         "hisitest1"         
#define PART_HISITEST2         "hisitest2"         
#define PART_SYSTEM            "system"            
#define PART_CUST              "cust"              
#define PART_USERDATA          "userdata"    

/*根据mmcblk编号引用,顺序必须和externel/efipartition中partitions[]顺序一致*/      
#define BLK_VRL               "/dev/block/mmcblk0p1"  
#define BLK_VRL_BKUP          "/dev/block/mmcblk0p2"  
#define BLK_MCUIMAGE          "/dev/block/mmcblk0p3"  
#define BLK_RESERVED0         "/dev/block/mmcblk0p4"  
#define BLK_FASTBOOT          "/dev/block/mmcblk0p5"  
#define BLK_MODEMNVBKUP       "/dev/block/mmcblk0p6"  
#define BLK_NVME              "/dev/block/mmcblk0p7"  
#define BLK_OEMINFO           "/dev/block/mmcblk0p8"  
#define BLK_SPLASH            "/dev/block/mmcblk0p9"  
#define BLK_MODEMNVM1         "/dev/block/mmcblk0p10"  
#define BLK_MODEMNVM2         "/dev/block/mmcblk0p11"  
#define BLK_MODEMNVM3         "/dev/block/mmcblk0p12"  
#define BLK_SECURETYSTORAGE   "/dev/block/mmcblk0p13"  
#define BLK_3RDMODEMNVM       "/dev/block/mmcblk0p14"  
#define BLK_3RDMODEMNVMBACK   "/dev/block/mmcblk0p15"  
#define BLK_RESERVED1         "/dev/block/mmcblk0p16"  
#define BLK_MODEMLOG          "/dev/block/mmcblk0p17"  
#define BLK_SPLASH2           "/dev/block/mmcblk0p18"  
#define BLK_MISC              "/dev/block/mmcblk0p19"  
#define BLK_MODEMNVRESERVED   "/dev/block/mmcblk0p20" 
#define BLK_RECOVERY2         "/dev/block/mmcblk0p21" 
#define BLK_RESERVED2         "/dev/block/mmcblk0p22"
#define BLK_TEEOS             "/dev/block/mmcblk0p23"
#define BLK_TRUSTFIRMWARE     "/dev/block/mmcblk0p24"  
#define BLK_SENSORHUB         "/dev/block/mmcblk0p25"  
#define BLK_HIFI              "/dev/block/mmcblk0p26"  
#define BLK_BOOT              "/dev/block/mmcblk0p27"  
#define BLK_RECOVERY          "/dev/block/mmcblk0p28"  
#define BLK_DTIMAGE           "/dev/block/mmcblk0p29"  
#define BLK_MODEMIMAGE        "/dev/block/mmcblk0p30"  
#define BLK_DSP               "/dev/block/mmcblk0p31"  
#define BLK_DFX               "/dev/block/mmcblk0p32"  
#define BLK_3RDMODEM          "/dev/block/mmcblk0p33"  
#define BLK_CACHE             "/dev/block/mmcblk0p34"  
#define BLK_HISITEST0         "/dev/block/mmcblk0p35"  
#define BLK_HISITEST1         "/dev/block/mmcblk0p36"  
#define BLK_HISITEST2         "/dev/block/mmcblk0p37"  
#define BLK_SYSTEM            "/dev/block/mmcblk0p38"  
#define BLK_CUST              "/dev/block/mmcblk0p39"  
#define BLK_USERDATA          "/dev/block/mmcblk0p40"  

/*根据block2mtd:mmcblk编号引用,顺序必须和externel/efipartition中partitions[]顺序一致*/ 
#define BLK_MTD_VRL               "block2mtd: /dev/block/mmcblk0p1"  
#define BLK_MTD_VRL_BKUP          "block2mtd: /dev/block/mmcblk0p2"  
#define BLK_MTD_MCUIMAGE          "block2mtd: /dev/block/mmcblk0p3"  
#define BLK_MTD_RESERVED0         "block2mtd: /dev/block/mmcblk0p4"  
#define BLK_MTD_FASTBOOT          "block2mtd: /dev/block/mmcblk0p5"  
#define BLK_MTD_MODEMNVBKUP       "block2mtd: /dev/block/mmcblk0p6"  
#define BLK_MTD_NVME              "block2mtd: /dev/block/mmcblk0p7"  
#define BLK_MTD_OEMINFO           "block2mtd: /dev/block/mmcblk0p8"  
#define BLK_MTD_SPLASH            "block2mtd: /dev/block/mmcblk0p9"  
#define BLK_MTD_MODEMNVM1         "block2mtd: /dev/block/mmcblk0p10"  
#define BLK_MTD_MODEMNVM2         "block2mtd: /dev/block/mmcblk0p11"  
#define BLK_MTD_MODEMNVM3         "block2mtd: /dev/block/mmcblk0p12"  
#define BLK_MTD_SECURETYSTORAGE   "block2mtd: /dev/block/mmcblk0p13"  
#define BLK_MTD_3RDMODEMNVM       "block2mtd: /dev/block/mmcblk0p14"  
#define BLK_MTD_3RDMODEMNVMBACK   "block2mtd: /dev/block/mmcblk0p15"  
#define BLK_MTD_RESERVED1         "block2mtd: /dev/block/mmcblk0p16"  
#define BLK_MTD_MODEMLOG          "block2mtd: /dev/block/mmcblk0p17"  
#define BLK_MTD_SPLASH2           "block2mtd: /dev/block/mmcblk0p18"  
#define BLK_MTD_MISC              "block2mtd: /dev/block/mmcblk0p19"  
#define BLK_MTD_MODEMNVRESERVED   "block2mtd: /dev/block/mmcblk0p20"
#define BLK_MTD_RECOVERY2         "block2mtd: /dev/block/mmcblk0p21"
#define BLK_MTD_RESERVED2         "block2mtd: /dev/block/mmcblk0p22"
#define BLK_MTD_TEEOS             "block2mtd: /dev/block/mmcblk0p23"
#define BLK_MTD_TRUSTFIRMWARE     "block2mtd: /dev/block/mmcblk0p24"  
#define BLK_MTD_SENSORHUB         "block2mtd: /dev/block/mmcblk0p25"  
#define BLK_MTD_HIFI              "block2mtd: /dev/block/mmcblk0p26"  
#define BLK_MTD_BOOT              "block2mtd: /dev/block/mmcblk0p27"  
#define BLK_MTD_RECOVERY          "block2mtd: /dev/block/mmcblk0p28"  
#define BLK_MTD_DTIMAGE           "block2mtd: /dev/block/mmcblk0p29"  
#define BLK_MTD_MODEMIMAGE        "block2mtd: /dev/block/mmcblk0p30"  
#define BLK_MTD_DSP               "block2mtd: /dev/block/mmcblk0p31"  
#define BLK_MTD_DFX               "block2mtd: /dev/block/mmcblk0p32"  
#define BLK_MTD_3RDMODEM          "block2mtd: /dev/block/mmcblk0p33"  
#define BLK_MTD_CACHE             "block2mtd: /dev/block/mmcblk0p34"  
#define BLK_MTD_HISITEST0         "block2mtd: /dev/block/mmcblk0p35"  
#define BLK_MTD_HISITEST1         "block2mtd: /dev/block/mmcblk0p36"  
#define BLK_MTD_HISITEST2         "block2mtd: /dev/block/mmcblk0p37"  
#define BLK_MTD_SYSTEM            "block2mtd: /dev/block/mmcblk0p38"  
#define BLK_MTD_CUST              "block2mtd: /dev/block/mmcblk0p39"  
#define BLK_MTD_USERDATA          "block2mtd: /dev/block/mmcblk0p40"  

#endif
